### ISSUE TITLE
No such device or address    --version13.5.2

### ISSUE THREAD

**Issue by winlj** [ThreeMammals/Ocelot#1017]
Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HLPSMKAMRU0A:00000007, previousRequestId: no previous request id, message: Error making http request, exception: System.Net.Http.HttpRequestException: No such device or address ---> System.Net.Sockets.SocketException: No such device or address
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         at System.Threading.Tasks.ValueTask`1.get_Result()
         at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Threading.Tasks.ValueTask`1.get_Result()
         at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
         at System.Threading.Tasks.ValueTask`1.get_Result()
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
         at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context)
==============================
{
  "GlobalConfiguration": {
    "ServiceDiscoveryProvider": {
      "Host": "192.168.0.6",
      "Port": 8500,
      "Type": "Consul"
    }
  },
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/code/{everything}",
      "DownstreamScheme": "http",
      "UpstreamPathTemplate": "/code/{everything}",
      "UpstreamHttpMethod": [ "GET", "POST" ],
      "UseServiceDiscovery": true,
      "ServiceName": "code.code.code",
      "LoadBalancerOptions": {
        "Type": "LeastConnection"
      }
    }
  ]
  //"QosOptions": {
  //  "ExceptionsAllowedBeforeBreaking": 3,
  //  "DurationOfBreak": 5,
  //  "TimeoutValue": 5000
  //}
}
===================================
public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddOcelot().AddConsul();
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.UseOcelot().Wait();
            app.UseMvc();
        }
    }

**Comment by karthik51** [comment]
Pls check your service name and hostname are same, if both are different, get this error message.

**Comment by raman-m** [comment]
It was misconfiguration issue!
Not real Ocelot bug.
