### ISSUE TITLE
BadRequest from Consul when Ocelot has no ReRoutes

### ISSUE THREAD

**Issue by jmezach** [ThreeMammals/Ocelot#1073]
## Expected Behavior
I'm storing my configuration for Ocelot in Consul. That means that I have a ServiceDiscoveryProvider section in my ocelot.json using Consul (as per the documentation). Without configuring any re-routes, dynamic re-routes or aggregates, I would expect a request going to `/` to result in an HTTP 404.

## Actual Behavior
A request going to `/` results in a 500 Internal Server Error.

## Steps to Reproduce the Problem
1. Setup Ocelot to use Consul for configuration
2. Put the following configuration in Consul, using the appropriate configuration key
```json
{
  "ReRoutes": [],
  "DynamicReRoutes": [],
  "Aggregates": [],
  "GlobalConfiguration": {
    "RequestIdKey": null,
    "ServiceDiscoveryProvider": {
      "Host": "localhost",
      "Port": 8500,
      "Type": null,
      "Token": null,
      "ConfigurationKey": "my-configuration-key",
      "PollingInterval": 0,
      "Namespace": null
    },
    "RateLimitOptions": {
      "ClientIdHeader": "ClientId",
      "QuotaExceededMessage": null,
      "RateLimitCounterPrefix": "ocelot",
      "DisableRateLimitHeaders": false,
      "HttpStatusCode": 429
    },
    "QoSOptions": {
      "ExceptionsAllowedBeforeBreaking": 0,
      "DurationOfBreak": 0,
      "TimeoutValue": 0
    },
    "BaseUrl": "www.example.com",
    "LoadBalancerOptions": {
      "Type": null,
      "Key": null,
      "Expiry": 0
    },
    "DownstreamScheme": null,
    "HttpHandlerOptions": {
      "AllowAutoRedirect": false,
      "UseCookieContainer": false,
      "UseTracing": false,
      "UseProxy": true
    }
  }
}
```
3. Run Ocelot
4. Do a request to the root URL where Ocelot is running
5. See a 500 Internal Server Error being returned

When I examined the log file, I see the following exception being logged:

```
[14:31:14 ERR] requestId: 80009da2-0000-6f00-b63f-84710c7967bb, previousRequestId: no previous request id, message: Exception caught in global error handler, exception message: Unexpected response, status code BadRequest: Missing service name, exception stack:    at Ocelot.Middleware.Pipeline.OcelotPipelineBuilderExtensions.<>c__DisplayClass5_2.<<UseMiddleware>b__3>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at Ocelot.Middleware.Pipeline.MapWhenMiddleware.Invoke(DownstreamContext context)

   at Ocelot.Errors.Middleware.ExceptionHandlerMiddleware.Invoke(DownstreamContext context) RequestId: 80009da2-0000-6f00-b63f-84710c7967bb

Consul.ConsulRequestException: Unexpected response, status code BadRequest: Missing service name

   at Ocelot.Middleware.Pipeline.OcelotPipelineBuilderExtensions.<>c__DisplayClass5_2.<<UseMiddleware>b__3>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at Ocelot.Middleware.Pipeline.MapWhenMiddleware.Invoke(DownstreamContext context)

   at Ocelot.Errors.Middleware.ExceptionHandlerMiddleware.Invoke(DownstreamContext context)
```

## Specifications

  - Version: 13.8.0
  - Platform: Windows
  - Subsystem: Consul

**Comment by raman-m** [comment]
### Misconfiguration issue!

Possible reasons
- Invalid setup for [Dynamic Routing](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html#dynamic-routing)
- Invalid Consul service instance deployment
- Ignoring [Dynamic Routing](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html#dynamic-routing) instructions
