### ISSUE TITLE
Error making http request

### ISSUE THREAD

**Issue by ihoeysun** [ThreeMammals/Ocelot#1158]
## question
  I use consul + ocelot, when the Kestrel at the same time open HTTP and HTTPS, when make consul server found gateway distribution of ocelot do will throw an Error: message: Error Code: UnableToCompleteRequestError message: Error making HTTP request

## ocelot logs
```
warn: Ocelot.Responder.Middleware.ResponderMiddleware[0]
      requestId: 0HLUCGCQ10LSQ:00000001, previousRequestId: no previous request id, message: Error Code: UnableToCompleteRequestError Message: Error making http request, exception: System.Net.Http.HttpRequestException: An error occurred while sending the request.
       ---> System.IO.IOException: The response ended prematurely.
         at System.Net.Http.HttpConnection.FillAsync()
         at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
         at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context) errors found in ResponderMiddleware. Setting error response for request path:/auth/token, request method: POST
```
## kestrel config
```
"Kestrel": {
	"Endpoints": {
		"Http": {
			"IsEnabled": true,
			"Url": "http://172.30.0.5:5050"
		},
		"HttpsInlineCertFile": {
			"IsEnabled": true,
			"Url": "https://172.30.0.5:443",
			"Certificate": {
				"Path": "TLS/client.pfx",
				"Password": "123123"
			}
		}
	}
}
```
## register consul config
```
var addresses = app.ServerFeatures.Get<IServerAddressesFeature>().Addresses.Select(p => new Uri(p));
            foreach (var address in addresses)
            {
                var serviceId = $"{serviceOptions.Value.ServiceName}_{address.Host}:{address.Port}";

                var httpCheck = new AgentServiceCheck()
                {
                    DeregisterCriticalServiceAfter = TimeSpan.FromMinutes(1),
                    Interval = TimeSpan.FromSeconds(5),
                    HTTP = new Uri(address, "health-check").OriginalString,
                    TLSSkipVerify = true,
                };
                var registration = new AgentServiceRegistration()
                {
                    Check = httpCheck,
                    Address = address.Host,
                    ID = serviceId,
                    Name = serviceOptions.Value.ServiceName,
                    Port = address.Port,
                    Tags = new[] { "用户中心,", address.Scheme, $"{address.Host}:{address.Port}" }
                };
            }
```
## consul 
![image](https://user-images.githubusercontent.com/41185330/77139089-9c296100-6aaf-11ea-81c8-40c7178ef326.png)
## ocelot.json
```
{
  "GlobalConfiguration": {
    "BaseUrl": "http://xx.xx.xxx.xxx:8066",
    "ServiceDiscoveryProvider": {
      "Host": "172.30.0.7",
      "Port": 8500
    }
  },
  "ReRoutes": [
    // account
    {
      "DownstreamPathTemplate": "/api/account/{url}",
      "DownstreamScheme": "http",
      "UpstreamPathTemplate": "/users/{url}",
      "UpstreamHttpMethod": [ "Post", "Get" ],
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "edu-servers",
        "AllowedScopes": []
      },
      "ServiceName": "service-accounts",
      "LoadBalancer": "LeastConnection",
      "UseServiceDiscovery": true
    },
    // identity
    {
      "DownstreamPathTemplate": "/connect/token",
      "DownstreamScheme": "http",
      "UpstreamPathTemplate": "/auth/token",
      "UpstreamHttpMethod": [ "Post" ],
      "ServiceName": "service-identity",
      "LoadBalancer": "LeastConnection",
      "UseServiceDiscovery": true
    }
  ]
} 

```

**Comment by raman-m** [comment]
How to solve what?

**Comment by raman-m** [comment]
Author's research. Custom setup was out of Ocelot team responsibilities.
