### ISSUE TITLE
Intermittent Socket exception

### ISSUE THREAD

**Issue by kcdivy** [ThreeMammals/Ocelot#1213]
## Error Description

At this moment we are getting **intermittent socket exception when same request is send consecutively**,
say for example if we send /testservice/swagger/v2/swagger.json 100 times consecutively we get socket exception 2 or 3 times. 

Our current deployment routing is  **nginx ingress -> ocelot gateway service -> downstream services**

The above said error is observed  only when the request is routed via ocelot . If we route directly from nginx gateway to downstream service(bypassing ocelot ) , no issues are observed

## Error
Please find the exception stack below,

warn: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HLV85R2EKNAA:00000001, previousRequestId: no previous request id, message: Error making http request, exception: System.Net.Http.HttpRequestException: Connection refused
       ---> System.Net.Sockets.SocketException (111): Connection refused
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
         at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context)
warn: Ocelot.Responder.Middleware.ResponderMiddleware[0]
      requestId: 0HLV85R2EKNAA:00000001, previousRequestId: no previous request id, message: Error Code: UnableToCompleteRequestError Message: Error making http request, exception: System.Net.Http.HttpRequestException: Connection refused
       ---> System.Net.Sockets.SocketException (111): Connection refused
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
         at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context) errors found in ResponderMiddleware. Setting error response for request path:/testservice/swagger/v2/swagger.json, request method: GET

## Ocelot setup
In **Startup.cs**,
            //Ocelot services
            services.AddOcelot()
                .AddDelegatingHandler<GlobalRequestResponseHandler>()
                .AddDelegatingHandler<ApiKeyHandler>();

In **Ocelot.json**, specific for path /testservice,

{
      "DownstreamPathTemplate": "/testservice/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "test-svc",
          "Port": 80
        }
      ],
      "UpstreamPathTemplate": "/testservice/{everything}",
      "UpstreamHttpMethod": [ "Get", "Options" ]
    }

_No handlers are used here._

**Am I missing some additional configuration or setup here ?**

## Specifications

  - Version:13.8.0

**Comment by benjamin-parker** [comment]
@kcdivy did you find a resolution for this?

**Comment by raman-m** [comment]
> "DownstreamScheme": "http",

You must use `ws` scheme (protocol)!

And read our updated docs please
 - [Websockets](https://ocelot.readthedocs.io/en/latest/features/websockets.html)
