### ISSUE TITLE
Ocelot returns 500 from Consul for the first request

### ISSUE THREAD

**Issue by chaitanyaphanikumar** [ThreeMammals/Ocelot#1294]
I have registered 3 services in Consul. (IdentityService is one of them). While trying to access this service through Ocelot, I had the below exception and Postman response returned 500 Internal server error.

Second request to this service returned 503 Service Unavailable.

Third request was Success and returned 200 OK.

Did I miss something to configure ?

Ocelot Configuration.json

{
      "DownstreamPathTemplate": "/api/v1/identity/register",
      "DownstreamScheme": "https",
      "UseServiceDiscovery": true,
      "ServiceName": "IdentityService",
      "UpstreamPathTemplate": "/v1/identity/register",
      "UpstreamHttpMethod": [ "POST" ],
      "LoadBalancerOptions": {
        "Type": "LeastConnection"
      }
    }
  ],
  "GlobalConfiguration": {
    "RequestIdKey": "OcRequestId",
    "BaseUrl": "https://localhost:44311",
    "ServiceDiscoveryProvider": {
      "Scheme": "http",
      "Host": "localhost",
      "Port": 8500,
      "Type": "Consul"
    }
  }

Exception (500 Reponse):-

Consul.ConsulRequestException: Unexpected response, status code ServiceUnavailable: 

</head><body id=ERR_CONNECT_FAIL>
<div id="titles">
<h1>ERROR</h1>
<h2>The requested URL could not be retrieved</h2>

<p>The following error was encountered while trying to retrieve the URL: <a href="http://localhost:8500/v1/health/service/IdentityService">http://localhost:8500/v1/health/service/IdentityService</a></p>

<blockquote id="error">
<p><b>Connection to ::1 failed.</b></p>

<p id="sysmsg">The system returned: <i>(111) Connection refused</i></p>

<p>The remote host or network may be down. Please try the request again.</p>

<p>Your cache administrator is <a href="mailto:webmaster?subject=CacheErrorInfo%20-%20ERR_CONNECT_FAIL&amp;body=CacheHost%3A%20moatcmn-deb1%0D%0AErrPage%3A%20ERR_CONNECT_FAIL%0D%0AErr%3A%20(111)%20Connection%20refused%0D%0ATimeStamp%3A%20Mon,%2020%20Jul%202020%2006%3A16%3A02%20GMT%0D%0A%0D%0AClientIP%3A%20172.21.206.228%0D%0AServerIP%3A%20localhost%0D%0A%0D%0AHTTP%20Request%3A%0D%0AGET%20%2Fv1%2Fhealth%2Fservice%2FIdentityService%20HTTP%2F1.1%0AAccept%3A%20application%2Fjson%0D%0AKeep-Alive%3A%20true%0D%0AHost%3A%20localhost%3A8500%0D%0A%0D%0A%0D%0A">webmaster</a>.</p>

<br>
</div>

<hr>
<div id="footer">
<p>Generated Mon, 20 Jul 2020 06:16:02 GMT by moatcmn-deb1 (squid/3.5.23)</p>

</div>
</body></html>

   at Consul.GetRequest`1.Execute(CancellationToken ct)
   at Ocelot.Provider.Consul.Consul.Get()
   at Ocelot.LoadBalancer.LoadBalancers.LoadBalancerFactory.<>c__DisplayClass2_0.<<Get>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Ocelot.LoadBalancer.LoadBalancers.LeastConnection.Lease(DownstreamContext downstreamContext)
   at Ocelot.LoadBalancer.Middleware.LoadBalancingMiddleware.Invoke(DownstreamContext context)
   at Ocelot.QueryStrings.Middleware.ClaimsToQueryStringMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Headers.Middleware.ClaimsToHeadersMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Authorisation.Middleware.AuthorisationMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Claims.Middleware.ClaimsToClaimsMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Authentication.Middleware.AuthenticationMiddleware.Invoke(DownstreamContext context)
   at Ocelot.RequestId.Middleware.ReRouteRequestIdMiddleware.Invoke(DownstreamContext context)
   at Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Request.Middleware.DownstreamRequestInitialiserMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Headers.Middleware.HttpHeadersTransformationMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Security.Middleware.SecurityMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Middleware.Multiplexer.Multiplexer.Fire(DownstreamContext context, OcelotRequestDelegate next)
   at Ocelot.Middleware.Multiplexer.Multiplexer.Multiplex(DownstreamContext context, ReRoute reRoute, OcelotRequestDelegate next)
   at Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Responder.Middleware.ResponderMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Middleware.Pipeline.MapWhenMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Errors.Middleware.ExceptionHandlerMiddleware.Invoke(DownstreamContext context) 
2020-07-20 11:46:01.3982||DEBUG|Ocelot.Errors.Middleware.ExceptionHandlerMiddleware|requestId: 0HM1CCO82S6AR:00000001, previousRequestId: no previous request id, message: ocelot pipeline finished 

Ocelot : 13.5.2
Net Core: 2.2

Any help is appreciated..

**Comment by lufeiyuan83** [comment]
hi chaitanyaphanikumar 
  I also have the problem, and did you fix it? any comments for me, thanks!

**Comment by lufeiyuan83** [comment]
hi  chaitanyaphanikumar 
    please update your Ocelot Configuration.json
{
"DownstreamPathTemplate": "/api/v1/identity/register",
"DownstreamScheme": "https",
"UseServiceDiscovery": true,
"ServiceName": "IdentityService",
"UpstreamPathTemplate": "/v1/identity/register",
"UpstreamHttpMethod": [ "POST" ],
"LoadBalancerOptions": {
"Type": "LeastConnection"
}
}
],
"GlobalConfiguration": {
"RequestIdKey": "OcRequestId",
"BaseUrl": "https://localhost:44311",
"ServiceDiscoveryProvider": {
"Scheme": "http",
"Host": "localhost",
"Port": 8500,
//////////////////////////////
 **_"Type": "PollConsul"_**
//////////////////////////////
}
}

**Comment by raman-m** [comment]
@chaitanyaphanikumar  Hi Chaitanya Phani Kumar!

Could you confirm, please, that @lufeiyuan83  advice helped to resolve the issue by changing provider type?

**Comment by raman-m** [comment]
The bug has been [accepted](#event-10307441319) due to open PR #1562
