### ISSUE TITLE
Ocelot - Error Code: UnableToCompleteRequestError

### ISSUE THREAD

**Issue by vvalpadasu** [ThreeMammals/Ocelot#1342]
requestId: 0HM1BKJGKQNVS:00000001, previousRequestId: no previous request id, message: Error Code: UnableToCompleteRequestError Message: Error making http request, exception: System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request. ---> System.Net.Sockets.SocketException: The I/O operation has been aborted because of either a thread exit or an application request
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context) errors found in ResponderMiddleware. Setting error response for request path:/xxxxx/xxxx/xxxx/xxxxxAffilations, request method: GET
2020-09-08 23:57:50,864 [11] INFO  - <Invoke>d__5 => MoveNext ==> Http Request Information:
Request Time: 9/8/2020 11:57:47 PM
Schema:http
Host: xxxx.xxxxxxxxx.com
Path: /xxxxx/xxxx/xxxx/xxxxxAffilations
QueryString: 
Request Body: 
Http Response Information:
Response Time: 9/8/2020 11:57:50 PM

StatusCode: 500

Response Body:

**Comment by raman-m** [comment]
Issue reported not using Bug template.
No steps to reproduce!
