### ISSUE TITLE
Forwarding Upstream HTTPS Request as Downstream HTTP Requests

### ISSUE THREAD

**Issue by graham-settle** [ThreeMammals/Ocelot#1343]
## Our Implementation
We have multiple tenants hosted on a single server. Each tenant has their own version of a micro-service running in docker containers. We are using Ocelot as an API gateway that forwards upstream requests from a tenant's clients to the tenant's version of the downstream micro-service. 

The API gateway is using the IIS **in-process** model (the ASP.NET Core module forwards requests to the IIS HTTP Server running in-process within IIS), as apposed to the IIS out-of-process model (the ASP.NET Core module forwards requests to its built-in web server Kestrel). Not sure if this relevant, but including just in case. 

The bindings for the API gateway site in IIS are configured for https. There is one binding per tenant. For example:
- https, tenant01.example.com, 9443
- https, tenant02.example.com, 9443

**Note**: 

1. app.UseHttpsRedirection() was removed from the Configure method of the Startup class of the API Gateway and micro-service.
2. DownstreamHostAndPorts.Port is mapped to the containers' internal port 80.

Here is an example of our ocelot.json file:

```
{
  "Routes": [
    {
      "UpstreamHost": "tenant01.example.com:9443",
      "UpstreamPathTemplate": "/api/loc-api/{everything}",
      "UpstreamHttpMethod": [ "GET", "POST", "PUT", "DELETE", "OPTIONS" ],
      "DownstreamPathTemplate": "/api/{everything}",
      "DownstreamSchema": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 51002
        },
    {
      "UpstreamHost": "tenant02.example.com:9443",
      "UpstreamPathTemplate": "/api/loc-api/{everything}",
      "UpstreamHttpMethod": [ "GET", "POST", "PUT", "DELETE", "OPTIONS" ],
      "DownstreamPathTemplate": "/api/{everything}",
      "DownstreamSchema": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 52002
        }
      ],
  "GlobalConfiguration": {
    "BaseUrl": "https://12.123.12.34:9443"
  }
}
```

## Expected Behavior / New Feature
Based on the configurations, we are expecting the API gateway/Ocelot to decrypt the clients' HTTPS requests and forward them to the micro-services as HTTP. I.e., the API gateway handles the HTTPS communication between the client and itself, and the communication between API gateway and the micro-services is handled as HTTP requests.  

## Actual Behavior / Motivation for New Feature
Per the following log output, it appears that Ocelot is forwarding the upstream requests to the downstream micro-services as HTTPS requests instead:

```
2020-09-17 18:44:26.0628||INFO|Microsoft.AspNetCore.Hosting.Diagnostics|Request starting HTTP/1.1 GET https://tenant02.example.com:9443/api/loc-api/roles
...
...
2020-09-17 18:44:26.1101||DEBUG|Ocelot.Errors.Middleware.ExceptionHandlerMiddleware|requestId: 80000148-0004-fd00-b63f-84710c7967bb, previousRequestId: no previous request id, message: ocelot pipeline started 
2020-09-17 18:44:26.1101||DEBUG|Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware|requestId: 80000148-0004-fd00-b63f-84710c7967bb, previousRequestId: no previous request id, message: Upstream url path is /api/loc-api/roles 
2020-09-17 18:44:26.1317||DEBUG|Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware|requestId: 80000148-0004-fd00-b63f-84710c7967bb, previousRequestId: no previous request id, message: downstream templates are /api/{everything} 
2020-09-17 18:44:26.1833||INFO|Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware|requestId: 80000148-0004-fd00-b63f-84710c7967bb, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /api/{everything} 
2020-09-17 18:44:26.1868||INFO|Ocelot.Authentication.Middleware.AuthenticationMiddleware|requestId: 80000148-0004-fd00-b63f-84710c7967bb, previousRequestId: no previous request id, message: No authentication needed for /api/loc-api/roles 
2020-09-17 18:44:26.1868||INFO|Ocelot.Authorisation.Middleware.AuthorisationMiddleware|requestId: 80000148-0004-fd00-b63f-84710c7967bb, previousRequestId: no previous request id, message: /api/{everything} route does not require user to be authorised 
2020-09-17 18:44:26.2015||DEBUG|Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware|requestId: 80000148-0004-fd00-b63f-84710c7967bb, previousRequestId: no previous request id, message: Downstream url is **https**://localhost:52002/api/roles 
2020-09-17 18:44:27.3598||DEBUG|Ocelot.Requester.Middleware.HttpRequesterMiddleware|requestId: 80000148-0004-fd00-b63f-84710c7967bb, previousRequestId: no previous request id, message: IHttpRequester returned an error, setting pipeline error 
2020-09-17 18:44:27.3725||WARN|Ocelot.Responder.Middleware.ResponderMiddleware|requestId: 80000148-0004-fd00-b63f-84710c7967bb, previousRequestId: no previous request id, message: Error Code: ConnectionToDownstreamServiceError Message: Error connecting to downstream service, exception: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: The handshake failed due to an unexpected packet format.
```
Which is causing the micro-service to through an exception: 
```
dbug: Microsoft.Extensions.Hosting.Internal.Host[2]
      Hosting started
dbug: Microsoft.AspNetCore.Server.Kestrel[39]
      Connection id "0HM2R76Q83EJC" accepted.
dbug: Microsoft.AspNetCore.Server.Kestrel[1]
      Connection id "0HM2R76Q83EJC" started.
dbug: Microsoft.AspNetCore.Server.Kestrel[17]
      Connection id "0HM2R76Q83EJC" bad request data: "Invalid request line: '\x16\x03\x03\x00\xA0\x01\x00\x00\x9C\x03\x03_c\xAE\x8B\xF3\x8E_M\xAD\xF4\xC8\xD0\xF0E`\xD3\x099\xF1\x08\xF1\x0B:i(\xD0\xC4tuZ\xAF\xF8\x00\x00*\xC0,\xC0+\xC00\xC0/\x00\x9F\x00\x9E\xC0$\xC0#\xC0(\xC0'\xC0\x0A'"
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Invalid request line: '\x16\x03\x03\x00\xA0\x01\x00\x00\x9C\x03\x03_c\xAE\x8B\xF3\x8E_M\xAD\xF4\xC8\xD0\xF0E`\xD3\x099\xF1\x08\xF1\x0B:i(\xD0\xC4tuZ\xAF\xF8\x00\x00*\xC0,\xC0+\xC00\xC0/\x00\x9F\x00\x9E\xC0$\xC0#\xC0(\xC0'\xC0\x0A'
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.RejectRequestLine(Byte* requestLine, Int32 length)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.GetUnknownMethod(Byte* data, Int32 length, Int32& methodLength)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, Byte* data, Int32 length)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.IHttpParser<TRequestHandler>.ParseRequestLine(TRequestHandler handler, ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TakeStartLine(ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.ParseRequest(ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TryParseRequest(ReadResult result, Boolean& endConnection)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
dbug: Microsoft.AspNetCore.Server.Kestrel[10]
      Connection id "0HM2R76Q83EJC" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HM2R76Q83EJC" stopped.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
      Connection id "0HM2R76Q83EJC" sending FIN because: "The Socket transport's send loop completed gracefully."
```

Is this the intended behavior to forward HTTPS request as HTTPS?
Or are we missing something in our configuration?

## Specifications

  - Version: 16.0.1
  - Platform: Windows Server 2019 (version 1809)
  - Subsystem: ASP.NET Core 3.1, IIS version 10

**Comment by jlukawska** [comment]
Hello, 
if your ocelot.json in this issue is exactly like in your application, the reason may be trivial: a typo. There should be "DownstreamSchem**e**", not "DownstreamSchem**a**".

**Comment by graham-settle** [comment]
Doh! yes that was the reason. The typo was also in the application's ocelot.json file. After I corrected it, the API gateway behaved as expected.

Thank you so much!
