### ISSUE TITLE
Wrong error code returned 401 => 502

### ISSUE THREAD

**Issue by dmitriy-pisarevskiy** [ThreeMammals/Ocelot#1415]
Hi! Original Swagger endpoint returned 401 (auth error) status code, but when I use Ocelot it proxy with 502 response. How I can resolve this issue to right proxy response code 401 => 401? 
in Logs I saw next:

info: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
      requestId: 0HM5KT0SKJEKF:0000000F, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /api/{everything}
info: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 0HM5KT0SKJEKF:0000000F, previousRequestId: no previous request id, message: No authentication needed for /api/v1.0/Discipline
info: Ocelot.Authorization.Middleware.AuthorizationMiddleware[0]
      requestId: 0HM5KT0SKJEKF:0000000F, previousRequestId: no previous request id, message: /api/{everything} route does not require user to be authorized
warn: Ocelot.Responder.Middleware.ResponderMiddleware[0]
      requestId: 0HM5KT0SKJEKF:0000000F, previousRequestId: no previous request id, message: Error Code: ConnectionToDownstreamServiceError Message: Error connecting to downstream service, exception: System.Net.Http.HttpRequestException: Error while copying content to a stream.
       ---> System.IO.IOException: The response ended prematurely.
         at System.Net.Http.HttpConnection.FillAsync(Boolean async)
         at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
         at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
         at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
         at Ocelot.Requester.HttpClientHttpRequester.GetResponse(HttpContext httpContext) errors found in ResponderMiddleware. Setting error response for request path:/api/v1.0/Discipline, request method: GET

**Comment by gao-artur** [comment]
You get 502 because Ocelot can't connect to downstream service, so the error code is correct.

> ConnectionToDownstreamServiceError Message: Error connecting to downstream service

Verify the `DownstreamHostAndPorts` is correct

**Comment by dmitriy-pisarevskiy** [comment]
> 
> 
> You get 502 because Ocelot can't connect to downstream service, so the error code is correct.
> 
> > ConnectionToDownstreamServiceError Message: Error connecting to downstream service
> 
> Verify the `DownstreamHostAndPorts` is correct

But when I refreshed JWT token all it's good 200 => 200 and check it directly. I saw problem when JWT is expired and service got 502 instead of 401

**Comment by raman-m** [comment]
@dmitriy-pisarevskiy 

Is this still the issue?
Do think does Ocelot still override the status code in your user scenario?

**Comment by dmitriy-pisarevskiy** [comment]
@raman-m ok, thanks. We can close this ticket, we already removed Ocelot.
