### ISSUE TITLE
Erratic 502 Error ConnectionToDownstreamServiceError

### ISSUE THREAD

**Issue by henrysmith** [ThreeMammals/Ocelot#1472]
I'm routing to an X service endpoint.  On the service side, I always get the routed Ocelot's call to the endpoint, and the service returns a 400 HTTP code.  Everything is logged.

When Ocelot gets the response from the service sometimes returns 400 but other times also returns 502  (ConnectionToDownstreamServiceError exception).   I can ensure that services X gets the call and always returns a 400 HTTP code. 

` IHttpRequester returned an error, setting pipeline error`
`ConnectionToDownstreamServiceError Message: Error connecting to downstream service, exception`

` "{Routes": [   {
      "DownstreamPathTemplate": "/{path}",
      "DownstreamScheme": "https",
      "Priority": 5,
      "DownstreamHostAndPorts": [
        {
          "Host": "my-downstream-service",
          "Port": 443
        }
      ],
      "UpstreamHttpMethod": [ "Post" ],
      "UpstreamPathTemplate": "/v1/{path}"
    } ],
  "GlobalConfiguration": {
    "BaseUrl": "http://localhost"
  }}`

## When returns HTTP code 400  (Expected behavior)

> info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://localhost:5020/v1/api/operation/runit text/plain 3306540
dbug: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      requestId: 0HM8PNITBGL5V:00000002, previousRequestId: no previous request id, message: ocelot pipeline started
dbug: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      requestId: 0HM8PNITBGL5V:00000002, previousRequestId: no previous request id, message: Upstream url path is /v1/api/operation/runit
dbug: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      requestId: 0HM8PNITBGL5V:00000002, previousRequestId: no previous request id, message: downstream templates are /{path}
info: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
      requestId: 0HM8PNITBGL5V:00000002, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /{path}
info: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 0HM8PNITBGL5V:00000002, previousRequestId: no previous request id, message: No authentication needed for /v1/api/operation/runit
info: Ocelot.Authorization.Middleware.AuthorizationMiddleware[0]
      requestId: 0HM8PNITBGL5V:00000002, previousRequestId: no previous request id, message: /{path} route does not require user to be authorized
dbug: Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware[0]
      requestId: 0HM8PNITBGL5V:00000002, previousRequestId: no previous request id, message: Downstream url is https://my-downstream-service/api/endoint
info: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HM8PNITBGL5V:00000002, previousRequestId: no previous request id, message: 400 (Bad Request) status code, request uri: https://my-downstream-service/api/endpoint
dbug: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HM8PNITBGL5V:00000002, previousRequestId: no previous request id, message: setting http response message
dbug: Ocelot.Responder.Middleware.ResponderMiddleware[0]
      requestId: 0HM8PNITBGL5V:00000002, previousRequestId: no previous request id, message: no pipeline errors, setting and returning completed response
dbug: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      requestId: 0HM8PNITBGL5V:00000002, previousRequestId: no previous request id, message: ocelot pipeline finished
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 POST http://localhost:5020/v1/api/operation/runit text/plain 3306540 - 400 282 application/problem+json;+charset=utf-8 616.7168ms

## When returns HTTP code 502  (Erratic behavior)

> info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://localhost:5020/v1/api/operation/runit text/plain 3306540
dbug: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      requestId: 0HM8PNJR0N9BG:00000002, previousRequestId: no previous request id, message: ocelot pipeline started
dbug: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      requestId: 0HM8PNJR0N9BG:00000002, previousRequestId: no previous request id, message: Upstream url path is /v1/api/operation/runit
dbug: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      requestId: 0HM8PNJR0N9BG:00000002, previousRequestId: no previous request id, message: downstream templates are /{path}
info: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
      requestId: 0HM8PNJR0N9BG:00000002, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /{path}
info: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 0HM8PNJR0N9BG:00000002, previousRequestId: no previous request id, message: No authentication needed for /v1/api/operation/runit
info: Ocelot.Authorization.Middleware.AuthorizationMiddleware[0]
      requestId: 0HM8PNJR0N9BG:00000002, previousRequestId: no previous request id, message: /{path} route does not require user to be authorized
dbug: Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware[0]
      requestId: 0HM8PNJR0N9BG:00000002, previousRequestId: no previous request id, message: Downstream url is https://my-downstream-service/api/endpoint
dbug: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HM8PNJR0N9BG:00000002, previousRequestId: no previous request id, message: IHttpRequester returned an error, setting pipeline error
warn: Ocelot.Responder.Middleware.ResponderMiddleware[0]
      requestId: 0HM8PNJR0N9BG:00000002, previousRequestId: no previous request id, message: Error Code: ConnectionToDownstreamServiceError Message: Error connecting to downstream service, exception: System.Net.Http.HttpRequestException: Error while copying content to a stream.
       ---> System.IO.IOException: The response ended prematurely.
         at System.Net.Http.HttpConnection.FillAsync(Boolean async)
         at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
         at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
         at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
         at Ocelot.Requester.HttpClientHttpRequester.GetResponse(HttpContext httpContext) errors found in ResponderMiddleware. Setting error response for request path:/v1/api/operation/runit, request method: POST
dbug: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      requestId: 0HM8PNJR0N9BG:00000002, previousRequestId: no previous request id, message: ocelot pipeline finished
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 POST http://localhost:5020/v1/api/operation/runit text/plain 3306540 - 502 0 - 824.4424ms

## Specifications

  - Version:  16.0.1
  - Platform: netCore 3.1

**Comment by henrysmith** [comment]
So,

We found that our service (via nginx proxy) can return Content-Length already calculated or it can return  _transfer-encoding: chunked_ .  

Ocelot doesn't work well with Chunked Encoding and for some reason (I don't really know) the connection gets closed. It might be that it's trying to read it twice or more.  

> Chunked Encoding - Ocelot will always get the body size and return Content-Length header. Sorry if this doesn’t work for your use case!

### Workaround 

So using EnableBuffering we ensure the request is there when Ocelots tries to process it. 

> Ensure the request can be read multiple times. Normally buffers request bodies in memory; writes requests larger than 30K bytes to disk.


```CSHARP
            app.Use(next => context =>
            {
                context.Request.EnableBuffering();

                return next(context);
            });
```

**Comment by henrysmith** [comment]
Well, my workaround (EnableBuffering) is making many other calls fail. I'm reinventing it back! Going back to the initial problem! 

Ocelot returns 502 Bad Gateway when _transfer-encoding: chunked_

**Comment by henrysmith** [comment]
Chunked transfer encoding is an HTTP/1.1 feature that enables keep-alive requests.  To avoid it, until we find a final solution, we can configure the routes to use HTTP/1.0, understanding that it requires a new connection for each resource downloaded.


```JSON
    {
      "DownstreamPathTemplate": "/{path}",
      "DownstreamScheme": "https",
      "Priority": 5,
      "DownstreamHostAndPorts": [
        {
          "Host": "my-downstream-service",
          "Port": 443
        }
      ],
      "DownstreamHttpVersion": "1.0",
      "UpstreamPathTemplate": "/my/{path}"
    }

```

**Comment by henrysmith** [comment]
A very important thing  I forgot to add is that this happens when the request is big.  In this case, we are sending a huge request.

**Comment by xianrui69** [comment]
+1

**Comment by raman-m** [comment]
@henrysmith  Hi Henry!
Thanks for reporting the issue!

Have you find some workaround and/or solution for this bug?

What about to test once again for last package v19.0.2, a release for .NET 7?
Will you be able to upgrade your gateway solution to .NET 7 with referencing to 19.0.2 package?

**Comment by ks1990cn** [comment]
@henrysmith @raman-m 
Interesting!!!! On latest version I tried to replicate before in https://github.com/ThreeMammals/Ocelot/issues/749 and gateway use to return 404 instead of 413. So my first question here is how is he not getting 404 as we faced on issue.

What is request body you are sending, if its less than 30 MB, then you should get 400 on server too (Which I have verified).

**Comment by raman-m** [comment]
@ks1990cn Tanmay,
Thanks for writing to this thread. But the author doesn't care! I wrote him in June, 6 months ago, and no feedback.
It seems the author is not with Ocelot anymore... It hard to discuss the case when there is no author in discussion.

**Comment by ggnaegi** [comment]
@raman-m it might be supported with the new request mapper though...

**Comment by raman-m** [comment]
@ggnaegi ok! Should we reopen this issue and attach to your PR?

3.3 Mb is a big request?! : 😂 see Author's log...
