### ISSUE TITLE
Exception on middleware if not call await next.Invoke()

### ISSUE THREAD

**Issue by vuta1927** [ThreeMammals/Ocelot#1488]
## Expected Behavior
Im current working on adding a custom middleware to do some logic check after request had Authorization check success. If the logic code check fails then return a json data in response.

## Actual Behavior
Ocelot fire an exception and return http response with code 500.

Ocelot.Errors.Middleware.ExceptionHandlerMiddleware
requestId: 0HM9L483Q0PCV:00000002, previousRequestId: no previous request id, message: Exception caught in global error handler, exception message: Object reference not set to an instance of an object., exception stack:    at Ocelot.Responder.HttpContextResponder.SetResponseOnHttpContext(HttpContext context, DownstreamResponse response)
   at Ocelot.Responder.Middleware.ResponderMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
   at Ocelot.Errors.Middleware.ExceptionHandlerMiddleware.Invoke(HttpContext httpContext) RequestId: 0HM9L483Q0PCV:00000002
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ocelot.Responder.HttpContextResponder.SetResponseOnHttpContext(HttpContext context, DownstreamResponse response)
   at Ocelot.Responder.Middleware.ResponderMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
   at Ocelot.Errors.Middleware.ExceptionHandlerMiddleware.Invoke(HttpContext httpContext)

## Steps to Reproduce the Problem
My Ocelot config with custom midleware in Startup
 var configuration = new OcelotPipelineConfiguration
            {
                AuthorizationMiddleware = async (ctx, next) =>
                {
                    if(some logic code)
                    {
                         await next.Invoke(); 
                         return;
                   } 
                           var jsonString = JsonConvert.SerializeObject(new ApiResponse(ApiStatusCode.InvalidClient, "Failed to validate."));
                          await ctx.Response.WriteAsync(jsonString, Encoding.UTF8);
               };

Is it a bug? Or did I miss something?

**Comment by MicroHeartWangZheng** [comment]
I also had the same problem

**Comment by abdulmoizlogiciel** [comment]
any resolution?
having same problem.

**Comment by raman-m** [comment]
We won't write the code instead of you, and not going to develop your solution...
