### ISSUE TITLE
API Gateways timeout errors with Ocelot

### ISSUE THREAD

**Issue by maruthi18081983** [ThreeMammals/Ocelot#1597]
## Expected Behavior / New Feature
We are using OCELOT gateway in .NetCore 3.1. When there are many requests going throw gateway we are getting the below timeout errors. We have already increased timeout in QOS options but it is getting failed even after 50 milliseconds where as micro service is returning the response but gateway not waiting and getting timeout. 
```json
  "HttpHandlerOptions":  {
    "AllowAutoRedirect": true,   
    "UseCookieContainer": true,              
    "UseTracing": true,             
    "MaxConnectionsPerServer": 5000
  },
  "QoSOptions": {
    "ExceptionsAllowedBeforeBreaking":99999,
    "DurationOfBreak":10000,
    "TimeoutValue":600000
}
```
## Steps to Reproduce the Problem
```
Category: Ocelot.Responder.Middleware.ResponderMiddleware
EventId: 0
RequestId: 80000b57-0005-ef00-b63f-84710c7967bb
RequestPath: /gw/api/test/GetInformation
SpanId: |7fde51f5-4f4d84f09af1eb1c.
TraceId: 7fde51f5-4f4d84f09af1eb1c
ParentId: 

requestId: 80000b57-0005-ef00-b63f-84710c7967bb, previousRequestId: no previous request id, message: Error Code: RequestTimedOutError Message: Timeout making http request, exception: System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Polly.Timeout.AsyncTimeoutEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Func`2 timeoutProvider, TimeoutStrategy timeoutStrategy, Func`5 onTimeoutAsync, Boolean continueOnCapturedContext)
   at Polly.Timeout.AsyncTimeoutEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Func`2 timeoutProvider, TimeoutStrategy timeoutStrategy, Func`5 onTimeoutAsync, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.<>c__DisplayClass3_0`1.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Polly.CircuitBreaker.AsyncCircuitBreakerPolicy.<>c__DisplayClass8_0`1.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Polly.CircuitBreaker.AsyncCircuitBreakerEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, ExceptionPredicates shouldHandleExceptionPredicates, ResultPredicates`1 shouldHandleResultPredicates, ICircuitController`1 breakerController)
   at Polly.CircuitBreaker.AsyncCircuitBreakerPolicy.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.ImplementationAsync[TResult](Func`3 func, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, IAsyncPolicy outerPolicy, IAsyncPolicy innerPolicy)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Ocelot.Provider.Polly.PollyCircuitBreakingDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context) errors found in ResponderMiddleware. Setting error response for request path:/api/test/GetInformation, request method: POST

Category: Ocelot.Requester.Middleware.HttpRequesterMiddleware
EventId: 0
RequestId: 80000b57-0005-ef00-b63f-84710c7967bb
RequestPath: /gw/api/test/GetInformation
SpanId: |7fde51f5-4f4d84f09af1eb1c.
TraceId: 7fde51f5-4f4d84f09af1eb1c
ParentId: 

requestId: 80000b57-0005-ef00-b63f-84710c7967bb, previousRequestId: no previous request id, message: Timeout making http request, exception: System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Polly.Timeout.AsyncTimeoutEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Func`2 timeoutProvider, TimeoutStrategy timeoutStrategy, Func`5 onTimeoutAsync, Boolean continueOnCapturedContext)
   at Polly.Timeout.AsyncTimeoutEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Func`2 timeoutProvider, TimeoutStrategy timeoutStrategy, Func`5 onTimeoutAsync, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.<>c__DisplayClass3_0`1.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Polly.CircuitBreaker.AsyncCircuitBreakerPolicy.<>c__DisplayClass8_0`1.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Polly.CircuitBreaker.AsyncCircuitBreakerEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, ExceptionPredicates shouldHandleExceptionPredicates, ResultPredicates`1 shouldHandleResultPredicates, ICircuitController`1 breakerController)
   at Polly.CircuitBreaker.AsyncCircuitBreakerPolicy.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.ImplementationAsync[TResult](Func`3 func, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, IAsyncPolicy outerPolicy, IAsyncPolicy innerPolicy)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Ocelot.Provider.Polly.PollyCircuitBreakingDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context)
```

## Specifications
  - Version: .NETCoreApp 3.1 
  - Platform: 
  - Subsystem:

**Comment by ks1990cn** [comment]
Hi @maruthi18081983 ,

I've done load testing, when I set `timeout in Ocelot.Json`  to 5000ms, my error rate stays 0% cause average response time comes to 1213ms, with total 9243 requests sent in 5 minutes(Considering ramp of 2 minutes). 
Which is approx 2.6 Million request per day, if its the case.. Ocelot is able to handle it.

When you say `you get many requests`, can you suggest rough Idea about how much, what is response time you get from hitting downstream API?

<img width="767" alt="image" src="https://github.com/ThreeMammals/Ocelot/assets/29522704/50e1f160-c77c-473c-bb3a-83a8e0c89894">

Following is observation when I reduced  `timeout in Ocelot.Json`  to 500ms, my error reached to 7.63% and which is expected cause response increases and QoS is working fine in this case.

<img width="767" alt="image" src="https://github.com/ThreeMammals/Ocelot/assets/29522704/6a3c7936-9cb6-4f8e-af4f-b02a6d730a3e">


@raman-m For me QoS is working as expected we just need to hear from @maruthi18081983 what he is doing, is he using any loadbalancer too (cause he claim he is getting many requests)?

**Comment by raman-m** [comment]
Tanmay, I'm sorry, but author's [repos are empty](https://github.com/maruthi18081983?tab=repositories) 👎 
You talk to ghost... 👻  There is no sense to talk to ghosts... 🤣

**Comment by raman-m** [comment]
> @ks1990cn commented [on Nov 26](#issuecomment-1826783772)

Thank you for this research!
Unfortunately I cannot view your pictures! Cannot open them when clicking!... Could you re-upload them once again plz?

-----
> @raman-m For me QoS is working as expected we just need to hear from @maruthi18081983 **what he is doing**, is he using any loadbalancer too (cause he claim he is getting many requests)?

He is doing that: Websockets (`ws` or `wss` scheme) with [Follow Redirects aka HttpHandlerOptions](https://ocelot.readthedocs.io/en/latest/features/configuration.html#follow-redirects-aka-httphandleroptions)

Look at the routing JSON:
The author tried QoS vs HttpHandlerOptions !!

Moreover, look at exception logs:
```
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
```
It seems the downstream services are Websocket ones! 🤣 

Isn't it idiotic to try QoS + Websockets + HttpHandlerOptions ? 👶  🤣

**Comment by raman-m** [comment]
@ks1990cn  Your load testing is awesome! We want more! 😉

**Comment by raman-m** [comment]
```json
"ExceptionsAllowedBeforeBreaking":99999,
```
Why not to assign 1 billion value? 🤣

**Comment by raman-m** [comment]
Your pics have JWT token in links! Sometimes I can open them, sometimes they are broken...
Could you re-upload them?
Did you save these pics?

**Comment by raman-m** [comment]
Pic1
![image](https://github.com/ThreeMammals/Ocelot/assets/10501504/8a32b3bb-e420-47e3-bae8-a41e1dfd3420)

Pic2
![image](https://github.com/ThreeMammals/Ocelot/assets/10501504/907f2a60-8461-4b26-a5b0-1d65d95fd873)
