### ISSUE TITLE
Ocelot:  UnableToCompleteRequestError 

### ISSUE THREAD

**Issue by clintcarter1999** [ThreeMammals/Ocelot#1601]
I added logging to the API Gateway which uses Ocelot.  This .Net Core 2.2 API is running on a linux server.
I added middleware to log the request IP address.

It appears to route requests just fine.

However, it never hits my middleware and instead is logging this exception from Ocelot.

```
[2022-09-15 17:02:50.5415][vmc-mercub][Warn] requestId: 0HMKNC1L9QQOG:00000001, previousRequestId: no previous request id, message: Error Code: **UnableToCompleteRequestError** Message: Error making http request, exception: System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> 
System.IO.IOException: Unable to read data from the transport connection: 
Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context) errors found in ResponderMiddleware. Setting error response for request path:/api/v1.0/Parts/Inventory, request method: POST 
```

Thoughts? Ideas? on what could be causing this?

**Comment by ks1990cn** [comment]
Can you share code hints of what and where you have put middleware?
