### ISSUE TITLE
Unstable integration tests

### ISSUE THREAD

**Issue by binarymash** [ThreeMammals/Ocelot#245]
Is anyone else seeing problems when running the integration tests, particularly on the command line? I'm not sure I've ever seen these run successfully on my own machine, even though they seem fine in appveyor.

The problems I see at the moment (build 3.1.6) are around these two tests:

-
 Ocelot.IntegrationTests.RaftTests.should_persist_command_to_five_servers_when_using_administration_api
- Ocelot.IntegrationTests.RaftTests.should_persist_command_to_five_servers

In particular, here are the errors...

1st run...

```
========================================
RunIntegrationTests
========================================
Test run for C:\dev\Ocelot\test\Ocelot.IntegrationTests\bin\Release\netcoreapp2.0\Ocelot.IntegrationTests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.5.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:01.4487492]   Discovering: Ocelot.IntegrationTests
[xUnit.net 00:00:01.5672036]   Discovered:  Ocelot.IntegrationTests
[xUnit.net 00:00:01.5765471]   Starting:    Ocelot.IntegrationTests
[xUnit.net 00:00:50.7556891]     Ocelot.IntegrationTests.RaftTests.should_persist_command_to_five_servers_when_using_administration_api [FAIL]
[xUnit.net 00:00:50.7586120]       Shouldly.ShouldAssertException : False
    should be
True
    but was not
[xUnit.net 00:00:50.7612035]       Stack Trace:
[xUnit.net 00:00:50.7645608]            at Shouldly.ShouldBeBooleanExtensions.ShouldBeTrue(Boolean actual, Func`1 customMessage)
Failed   Ocelot.IntegrationTests.RaftTests.should_persist_command_to_five_servers_when_using_administration_api
Error Message:
 Shouldly.ShouldAssertException : False
    should be
True
    but was not
Stack Trace:
   at Shouldly.ShouldBeBooleanExtensions.ShouldBeTrue(Boolean actual, Func`1 customMessage)
[xUnit.net 00:00:50.8686009]     Ocelot.IntegrationTests.RaftTests.should_persist_command_to_five_servers [FAIL]
[xUnit.net 00:00:50.8689084]       System.AggregateException : One or more errors occurred. (Access to the path 'C:\dev\Ocelot\test\Ocelot.IntegrationTests\bin\Release\netcoreapp2.0\configuration.json' is denied.) (Object reference not set to an instance of an object.)
[xUnit.net 00:00:50.8692560]       ---- System.UnauthorizedAccessException : Access to the path 'C:\dev\Ocelot\test\Ocelot.IntegrationTests\bin\Release\netcoreapp2.0\configuration.json' is denied.
[xUnit.net 00:00:50.8697792]       ---- System.NullReferenceException : Object reference not set to an instance of an object.
[xUnit.net 00:00:50.8704196]       Stack Trace:
[xUnit.net 00:00:50.8705483]
[xUnit.net 00:00:50.8705977]         ----- Inner Stack Trace #1 (System.UnauthorizedAccessException) -----
[xUnit.net 00:00:50.8707371]            at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
[xUnit.net 00:00:50.8708801]            at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
[xUnit.net 00:00:50.8711665]            at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
[xUnit.net 00:00:50.8715073]            at System.IO.StreamWriter..ctor(String path)
[xUnit.net 00:00:50.8716679]            at System.IO.File.WriteAllText(String path, String contents)
[xUnit.net 00:00:50.8719204]         C:\dev\Ocelot\test\Ocelot.IntegrationTests\RaftTests.cs(323,0): at Ocelot.IntegrationTests.RaftTests.GivenThereIsAConfiguration(FileConfiguration fileConfiguration)
[xUnit.net 00:00:50.8721258]         C:\dev\Ocelot\test\Ocelot.IntegrationTests\RaftTests.cs(114,0): at Ocelot.IntegrationTests.RaftTests.should_persist_command_to_five_servers()
[xUnit.net 00:00:50.8724573]         ----- Inner Stack Trace #2 (System.NullReferenceException) -----
[xUnit.net 00:00:50.8730717]         C:\dev\Ocelot\test\Ocelot.IntegrationTests\RaftTests.cs(55,0): at Ocelot.IntegrationTests.RaftTests.Dispose()
[xUnit.net 00:00:50.8738697]         C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs(76,0): at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)
Failed   Ocelot.IntegrationTests.RaftTests.should_persist_command_to_five_servers
Error Message:
 System.AggregateException : One or more errors occurred. (Access to the path 'C:\dev\Ocelot\test\Ocelot.IntegrationTests\bin\Release\netcoreapp2.0\configuration.json' is denied.) (Object reference not set to an instance of an object.)
---- System.UnauthorizedAccessException : Access to the path 'C:\dev\Ocelot\test\Ocelot.IntegrationTests\bin\Release\netcoreapp2.0\configuration.json' is denied.
---- System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:

----- Inner Stack Trace #1 (System.UnauthorizedAccessException) -----
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at System.IO.File.WriteAllText(String path, String contents)
   at Ocelot.IntegrationTests.RaftTests.GivenThereIsAConfiguration(FileConfiguration fileConfiguration) in C:\dev\Ocelot\test\Ocelot.IntegrationTests\RaftTests.cs:line 323
   at Ocelot.IntegrationTests.RaftTests.should_persist_command_to_five_servers() in C:\dev\Ocelot\test\Ocelot.IntegrationTests\RaftTests.cs:line 114
----- Inner Stack Trace #2 (System.NullReferenceException) -----
   at Ocelot.IntegrationTests.RaftTests.Dispose() in C:\dev\Ocelot\test\Ocelot.IntegrationTests\RaftTests.cs:line 55
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 76
[xUnit.net 00:00:53.7606422]   Finished:    Ocelot.IntegrationTests

Total tests: 11. Passed: 9. Failed: 2. Skipped: 0.
Test Run Failed.
Test execution time: 56.3438 Seconds
An error occurred when executing task 'RunIntegrationTests'.
Error: One or more errors occurred.
        .NET Core CLI: Process returned an error (exit code 1).
```

2nd run...

```
========================================
RunIntegrationTests
========================================
Test run for C:\dev\Ocelot\test\Ocelot.IntegrationTests\bin\Release\netcoreapp2.0\Ocelot.IntegrationTests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.5.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:01.2935945]   Discovering: Ocelot.IntegrationTests
[xUnit.net 00:00:01.3903030]   Discovered:  Ocelot.IntegrationTests
[xUnit.net 00:00:01.4048626]   Starting:    Ocelot.IntegrationTests
[xUnit.net 00:01:21.8609788]     Ocelot.IntegrationTests.RaftTests.should_persist_command_to_five_servers [FAIL]
[xUnit.net 00:01:21.8634676]       Shouldly.ShouldAssertException : False
    should be
True
    but was not
[xUnit.net 00:01:21.8661674]       Stack Trace:
[xUnit.net 00:01:21.8675896]            at Shouldly.ShouldBeBooleanExtensions.ShouldBeTrue(Boolean actual, Func`1 customMessage)
[xUnit.net 00:01:21.8739891]   Finished:    Ocelot.IntegrationTests
Failed   Ocelot.IntegrationTests.RaftTests.should_persist_command_to_five_servers
Error Message:
 Shouldly.ShouldAssertException : False
    should be
True
    but was not
Stack Trace:
   at Shouldly.ShouldBeBooleanExtensions.ShouldBeTrue(Boolean actual, Func`1 customMessage)

Total tests: 11. Passed: 10. Failed: 1. Skipped: 0.
Test Run Failed.
Test execution time: 1.3859 Minutes
An error occurred when executing task 'RunIntegrationTests'.
Error: One or more errors occurred.
        .NET Core CLI: Process returned an error (exit code 1).
```

3rd run...

```
========================================
RunIntegrationTests
========================================
Test run for C:\dev\Ocelot\test\Ocelot.IntegrationTests\bin\Release\netcoreapp2.0\Ocelot.IntegrationTests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.5.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:01.3577134]   Discovering: Ocelot.IntegrationTests
[xUnit.net 00:00:01.4637853]   Discovered:  Ocelot.IntegrationTests
[xUnit.net 00:00:01.4784219]   Starting:    Ocelot.IntegrationTests
[xUnit.net 00:00:48.6151504]     Ocelot.IntegrationTests.RaftTests.should_persist_command_to_five_servers_when_using_administration_api [FAIL]
[xUnit.net 00:00:48.6171011]       Shouldly.ShouldAssertException : False
    should be
True
    but was not
[xUnit.net 00:00:48.6190835]       Stack Trace:
[xUnit.net 00:00:48.6208924]            at Shouldly.ShouldBeBooleanExtensions.ShouldBeTrue(Boolean actual, Func`1 customMessage)
Failed   Ocelot.IntegrationTests.RaftTests.should_persist_command_to_five_servers_when_using_administration_api
Error Message:
 Shouldly.ShouldAssertException : False
    should be
True
    but was not
Stack Trace:
   at Shouldly.ShouldBeBooleanExtensions.ShouldBeTrue(Boolean actual, Func`1 customMessage)
[xUnit.net 00:00:48.6381473]     Ocelot.IntegrationTests.RaftTests.should_persist_command_to_five_servers [FAIL]
[xUnit.net 00:00:48.6383069]       System.AggregateException : One or more errors occurred. (Access to the path 'C:\dev\Ocelot\test\Ocelot.IntegrationTests\bin\Release\netcoreapp2.0\configuration.json' is denied.) (Object reference not set to an instance of an object.)
[xUnit.net 00:00:48.6383445]       ---- System.UnauthorizedAccessException : Access to the path 'C:\dev\Ocelot\test\Ocelot.IntegrationTests\bin\Release\netcoreapp2.0\configuration.json' is denied.
[xUnit.net 00:00:48.6383699]       ---- System.NullReferenceException : Object reference not set to an instance of an object.
[xUnit.net 00:00:48.6384155]       Stack Trace:
[xUnit.net 00:00:48.6384644]
[xUnit.net 00:00:48.6385078]         ----- Inner Stack Trace #1 (System.UnauthorizedAccessException) -----
[xUnit.net 00:00:48.6385627]            at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
[xUnit.net 00:00:48.6386260]            at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
[xUnit.net 00:00:48.6386983]            at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
[xUnit.net 00:00:48.6387708]            at System.IO.StreamWriter..ctor(String path)
[xUnit.net 00:00:48.6388288]            at System.IO.File.WriteAllText(String path, String contents)
[xUnit.net 00:00:48.6389183]         C:\dev\Ocelot\test\Ocelot.IntegrationTests\RaftTests.cs(323,0): at Ocelot.IntegrationTests.RaftTests.GivenThereIsAConfiguration(FileConfiguration fileConfiguration)
[xUnit.net 00:00:48.6390120]         C:\dev\Ocelot\test\Ocelot.IntegrationTests\RaftTests.cs(114,0): at Ocelot.IntegrationTests.RaftTests.should_persist_command_to_five_servers()
[xUnit.net 00:00:48.6390803]         ----- Inner Stack Trace #2 (System.NullReferenceException) -----
[xUnit.net 00:00:48.6391424]         C:\dev\Ocelot\test\Ocelot.IntegrationTests\RaftTests.cs(55,0): at Ocelot.IntegrationTests.RaftTests.Dispose()
[xUnit.net 00:00:48.6391900]         C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs(76,0): at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)
[xUnit.net 00:00:48.6453216]   Finished:    Ocelot.IntegrationTests
Failed   Ocelot.IntegrationTests.RaftTests.should_persist_command_to_five_servers
Error Message:
 System.AggregateException : One or more errors occurred. (Access to the path 'C:\dev\Ocelot\test\Ocelot.IntegrationTests\bin\Release\netcoreapp2.0\configuration.json' is denied.) (Object reference not set to an instance of an object.)
---- System.UnauthorizedAccessException : Access to the path 'C:\dev\Ocelot\test\Ocelot.IntegrationTests\bin\Release\netcoreapp2.0\configuration.json' is denied.
---- System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:

----- Inner Stack Trace #1 (System.UnauthorizedAccessException) -----
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at System.IO.File.WriteAllText(String path, String contents)
   at Ocelot.IntegrationTests.RaftTests.GivenThereIsAConfiguration(FileConfiguration fileConfiguration) in C:\dev\Ocelot\test\Ocelot.IntegrationTests\RaftTests.cs:line 323
   at Ocelot.IntegrationTests.RaftTests.should_persist_command_to_five_servers() in C:\dev\Ocelot\test\Ocelot.IntegrationTests\RaftTests.cs:line 114
----- Inner Stack Trace #2 (System.NullReferenceException) -----
   at Ocelot.IntegrationTests.RaftTests.Dispose() in C:\dev\Ocelot\test\Ocelot.IntegrationTests\RaftTests.cs:line 55
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 76

Total tests: 11. Passed: 9. Failed: 2. Skipped: 0.
Test Run Failed.
Test execution time: 49.9615 Seconds
An error occurred when executing task 'RunIntegrationTests'.
Error: One or more errors occurred.
        .NET Core CLI: Process returned an error (exit code 1).
```

4th run...

```
========================================
RunIntegrationTests
========================================
Test run for C:\dev\Ocelot\test\Ocelot.IntegrationTests\bin\Release\netcoreapp2.0\Ocelot.IntegrationTests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.5.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:01.7436337]   Discovering: Ocelot.IntegrationTests
[xUnit.net 00:00:01.8528124]   Discovered:  Ocelot.IntegrationTests
[xUnit.net 00:00:01.8641031]   Starting:    Ocelot.IntegrationTests
[xUnit.net 00:00:45.8377771]     Ocelot.IntegrationTests.RaftTests.should_persist_command_to_five_servers_when_using_administration_api [FAIL]
[xUnit.net 00:00:45.8397419]       Shouldly.ShouldAssertException : False
    should be
True
    but was not
[xUnit.net 00:00:45.8414982]       Stack Trace:
[xUnit.net 00:00:45.8433529]            at Shouldly.ShouldBeBooleanExtensions.ShouldBeTrue(Boolean actual, Func`1 customMessage)
Failed   Ocelot.IntegrationTests.RaftTests.should_persist_command_to_five_servers_when_using_administration_api
Error Message:
 Shouldly.ShouldAssertException : False
    should be
True
    but was not
Stack Trace:
   at Shouldly.ShouldBeBooleanExtensions.ShouldBeTrue(Boolean actual, Func`1 customMessage)
[xUnit.net 00:01:21.4538003]   Finished:    Ocelot.IntegrationTests

Total tests: 11. Passed: 10. Failed: 1. Skipped: 0.
Test Run Failed.
Test execution time: 1.3804 Minutes
An error occurred when executing task 'RunIntegrationTests'.
Error: One or more errors occurred.
        .NET Core CLI: Process returned an error (exit code 1).
```

**Comment by TomPallister** [comment]
@binarymash yeh these two are flakey. I think they should be ignored for now as they are for the raft implementation which is very experimental and is flagged as such in the Oceot guide. 

However I do intend to fix them one day because I would like this feature to work there are just other priorities at the moment. I think request aggregation is the big feature that users need.

If they want to have Ocelot in a cluster working well then the recommended approach is to use consul at the moment!

I will push a commit to ignore them but leave this issue open for long term fix.

**Comment by TomPallister** [comment]
need to fix this https://github.com/ThreeMammals/Rafty/pull/11 first
