### ISSUE TITLE
Unhandled Exception: Consul.ConsulRequestException: Unexpected response, status code InternalServerError: rpc error: connection is shut down

### ISSUE THREAD

**Issue by guoming** [ThreeMammals/Ocelot#293]
## Steps to Reproduce the Problem

Unhandled Exception: Consul.ConsulRequestException: Unexpected response, status code InternalServerError: rpc error: connection is shut down
   at Consul.GetRequest`1.<Execute>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Consul.KV.<Get>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Ocelot.Configuration.Repository.ConsulFileConfigurationRepository.<Get>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Ocelot.Configuration.Repository.ConsulFileConfigurationPoller.<Poll>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.Configuration.Repository.ConsulFileConfigurationPoller.<<-ctor>b__6_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by TomPallister** [comment]
@guoming Thanks for your interest in the project :) I have a few questions that will help work out what the problem is.

Is your consul instance accessible? 

Can you see the object with key "OcelotConfiguration" in your consul KeyValue store?

Please could you paste your configuration.json and startup.cs / program.cs files?
