### ISSUE TITLE
when i used the code to test ,It is not function on app.ApplicationServices.GetServices<IFileConfigurationSetter>() 

### ISSUE THREAD

**Issue by dasajia2lang** [ThreeMammals/Ocelot#305]
## Steps to Reproduce the Problem

  1.app.ApplicationServices.GetServices<IFileConfigurationSetter>(),when code runing here,it is error ,

Unable to resolve service for type 'Microsoft.AspNetCore.Hosting.IWebHostBuilder' while attempting to activate 'Ocelot.Middleware.BaseUrlFinder
  2. at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateEnumerable(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType, ServiceProvider serviceProvider)
   at System.Collections.Concurrent.ConcurrentDictionaryExtensions.GetOrAdd[TKey,TValue,TArg](ConcurrentDictionary`2 dictionary, TKey key, Func`3 valueFactory, TArg arg)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices[T](IServiceProvider provider)
   at OcelotAPIGateWay.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in E:\MyItems\OctorApiGateWay\OcelotAPIGateWay\Startup.cs:line 40
  3.i see，this service Is already add in IServiceCollection in  OcelotBuilder 

## Specifications

  - Version:master/2018-4-8
  - Platform:net core 2.0
  - Subsystem:window

**Comment by TomPallister** [comment]
@dasajia2lang thanks for your interest in the project! What version of Ocelot are you using?

**Comment by dasajia2lang** [comment]
I pull the lastest code from git。the branch is master。date is 2018-4-8

**Comment by dasajia2lang** [comment]
@TomPallister ， I pull the lastest code from git。the branch is master。date is 2018-4-8

**Comment by TomPallister** [comment]
@dasajia2lang The error you are getting suggests that BaseUrlFinder has a dependency on IWebHostBuilder (which it used to do in previous versions of Ocelot). If you look at the code you have cloned and are using does BaseUrlFinder take IWebHostBuilder  in it's constructor?

You can see the current code [here](https://github.com/ThreeMammals/Ocelot/blob/master/src/Ocelot/Middleware/BaseUrlFinder.cs) and BaseUrlFinder does not take the IWebHostBuilder.

If your cloned code looks OK, can you double check that you are not referencing an older dll (e.g. NuGet package) or just the wrong branch of the cloned Ocelot.

**Comment by dasajia2lang** [comment]
@TomPallister ，yes，the BaseUrlFinder is  constructor is depenency the IWebHostBuilder. I cloned the master branch today ,the code is right .thank you for you answer!!

**Comment by TomPallister** [comment]
No problem :)
