### ISSUE TITLE
Ocelot deletes configuration file at startup

### ISSUE THREAD

**Issue by seroche** [ThreeMammals/Ocelot#373]
Whenever I load Ocelot from my Windows Server 2016 Core Server (IIS10) I get an exception.

Apparently for some reasons, Ocelot is trying to delete my configuration. As the app pool is running with limited privileges, I get an access denied. 

I'm not 100% sure to understand why this is happening.

Unhandled Exception: System.UnauthorizedAccessException: Access to the path 'C:\inetpub\AspNetCoreWebApps\TEC.CoreApi.Dispatcher\ocelot.Staging.json' is denied.
   at System.IO.Win32FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Ocelot.Configuration.Repository.DiskFileConfigurationRepository.Set(FileConfiguration fileConfiguration)
   at Ocelot.Configuration.Setter.FileAndInternalConfigurationSetter.<Set>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.Middleware.OcelotMiddlewareExtensions.<SetFileConfig>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.Middleware.OcelotMiddlewareExtensions.<CreateConfiguration>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.Middleware.OcelotMiddlewareExtensions.<UseOcelot>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.Middleware.OcelotMiddlewareExtensions.<UseOcelot>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TEC.CoreApi.Dispatcher.Startup.<Configure>d__5.MoveNext() in C:\Repository\core-api\src\TEC.CoreApi.Dispatcher\Startup.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

## Specifications

  - Version: 7.0.4 with .net core 2.0.7
  - Platform: Windows Server 2016 with IIS 10
  - Subsystem: IISIntegration used

**Comment by gurame** [comment]
I got the same error working with aws lambda. Everything inside aws lambda is read-only. 

System.IO.IOException: Read-only file system
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at System.IO.File.WriteAllText(String path, String contents)
   at Ocelot.Configuration.Repository.DiskFileConfigurationRepository.Set(FileConfiguration fileConfiguration)
   at Ocelot.Configuration.Setter.FileAndInternalConfigurationSetter.<Set>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.Middleware.OcelotMiddlewareExtensions.<SetFileConfig>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.Middleware.OcelotMiddlewareExtensions.<CreateConfiguration>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.Middleware.OcelotMiddlewareExtensions.<UseOcelot>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.Middleware.OcelotMiddlewareExtensions.<UseOcelot>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by CuddleBunny** [comment]
I am also experiencing this issue when running in a single node local Service Fabric cluster. I don't even have an `ocelot.Production.json` being loaded.

**Comment by TomPallister** [comment]
@seroche @gurame @CuddleBunny this is happening because Ocelot persists it's state to ocelot.json or ocelot.{environment}.json if applicable. Ocelot has an adminstration API so that its configuration can be changed while Ocelot is running. When changes are made we wan't to persist them.

When I originally wrote Ocelot I imagined that it would always be hosted in a docker container with access to write to its own volumes but as the project has become more popular people are hosting Ocelot in different ways that I did not account for.

Another problem is that Ocelot supports a scenario where the user can have multiple configurations that get merged into one see [here](http://ocelot.readthedocs.io/en/latest/features/configuration.html#merging-configuration-files). Ocelot merges these into one json file and writes that to disk and would use it to persist state.

I guess the answer is to not try and write to disk unless the user is either merging configuration files or using the administration api to update configuration files. This is something that I can start looking at in the next few weeks but I will not be able to change it super quickly as the code around configuration is a bit crap and might need some extra thinking. If any of you fancy a challenge I would welcome a PR but this is a tricky part of the software so don't worry if not! 😄 

@CuddleBunny there is probably something with Service Fabric where you get different admin perms on a 5 node cluster or something! Who knows though :(

**Comment by anh072** [comment]
hey can you solve this for merging config files as well? I deployed it to an IIS server, and I have this problem

**Comment by Jedi0098** [comment]
Well I do not know why, maybe host confusion but for me the issue has solve when I use this
                    webBuilder.UseUrls("http://localhost:5020", "https://localhost:5021");
