### ISSUE TITLE
Delegating Handler Exceptions

### ISSUE THREAD

**Issue by SnailDev** [ThreeMammals/Ocelot#438]
## Steps to Reproduce the Problem
  1. just write delegeting handler like doc mentioned.
```C#
    public class FakeHandler : DelegatingHandler
    {
        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            Console.WriteLine(request.RequestUri);

            //do stuff and optionally call the base handler..
            return await base.SendAsync(request, cancellationToken);
        }
    }
```
  2.Next you must add the handlers to Ocelot’s container either as singleton like follows.
```C#
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddOcelot()
                .AddSingletonDelegatingHandler<FakeHandler>(true);
        }
```
  3. request 10 times.

Exceptions:
```bash
info: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
      requestId: 0HLES1VH2VLE4:00000002, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /api/values
info: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 0HLES1VH2VLE4:00000002, previousRequestId: no previous request id, message: No authentication needed for /api001/values
info: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0]
      requestId: 0HLES1VH2VLE4:00000002, previousRequestId: no previous request id, message: /api/values route does not require user to be authorised
http://192.168.2.8:5001/api/values
info: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
      requestId: 0HLES1VH2VLE4:00000003, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /api/values
info: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 0HLES1VH2VLE4:00000003, previousRequestId: no previous request id, message: No authentication needed for /api001/values
info: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0]
      requestId: 0HLES1VH2VLE4:00000003, previousRequestId: no previous request id, message: /api/values route does not require user to be authorised
http://192.168.2.8:5001/api/values
info: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
      requestId: 0HLES1VH2VLE4:00000004, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /api/values
info: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 0HLES1VH2VLE4:00000004, previousRequestId: no previous request id, message: No authentication needed for /api001/values
info: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0]
      requestId: 0HLES1VH2VLE4:00000004, previousRequestId: no previous request id, message: /api/values route does not require user to be authorised
fail: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      requestId: 0HLES1VH2VLE4:00000004, previousRequestId: no previous request id, message: Exception caught in global error handler, exception message: This instance has already started one or more requests. Properties can only be modified before sending the first request., exception stack:    at System.Net.Http.DelegatingHandler.CheckDisposedOrStarted()
         at System.Net.Http.DelegatingHandler.set_InnerHandler(HttpMessageHandler value)
         at Ocelot.Requester.HttpClientBuilder.<>c__DisplayClass13_0.<CreateHttpMessageHandler>b__1(Func`1 handler) in D:\SnailProject\Ocelot\src\Ocelot\Requester\HttpClientBuilder.cs:line 124
         at System.Collections.Generic.List`1.ForEach(Action`1 action)
         at Ocelot.Requester.HttpClientBuilder.CreateHttpMessageHandler(HttpMessageHandler httpMessageHandler, DownstreamReRoute request) in D:\SnailProject\Ocelot\src\Ocelot\Requester\HttpClientBuilder.cs:line 117
         at Ocelot.Requester.HttpClientBuilder.Create(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\Requester\HttpClientBuilder.cs:line 60
         at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\Requester\HttpClientHttpRequester.cs:line 31
         at Ocelot.Requester.Middleware.HttpRequesterMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\Requester\Middleware\HttpRequesterMiddleware.cs:line 23
         at Ocelot.Cache.Middleware.OutputCacheMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\Cache\Middleware\OutputCacheMiddleware.cs:line 33
         at Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\DownstreamUrlCreator\Middleware\DownstreamUrlCreatorMiddleware.cs:line 57
         at Ocelot.LoadBalancer.Middleware.LoadBalancingMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\LoadBalancer\Middleware\LoadBalancingMiddleware.cs:line 50
         at Ocelot.QueryStrings.Middleware.QueryStringBuilderMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\QueryStrings\Middleware\QueryStringBuilderMiddleware.cs:line 42
         at Ocelot.Headers.Middleware.HttpRequestHeadersBuilderMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\Headers\Middleware\HttpRequestHeadersBuilderMiddleware.cs:line 44
         at Ocelot.Authorisation.Middleware.AuthorisationMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\Authorisation\Middleware\AuthorisationMiddleware.cs:line 86
         at Ocelot.Claims.Middleware.ClaimsBuilderMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\Claims\Middleware\ClaimsBuilderMiddleware.cs:line 42
         at Ocelot.Authentication.Middleware.AuthenticationMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\Authentication\Middleware\AuthenticationMiddleware.cs:line 52
         at Ocelot.RequestId.Middleware.ReRouteRequestIdMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\RequestId\Middleware\ReRouteRequestIdMiddleware.cs:line 30
         at Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\RateLimit\Middleware\ClientRateLimitMiddleware.cs:line 38
         at Ocelot.Request.Middleware.DownstreamRequestInitialiserMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\Request\Middleware\DownstreamRequestInitialiserMiddleware.cs:line 39
         at Ocelot.Headers.Middleware.HttpHeadersTransformationMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\Headers\Middleware\HttpHeadersTransformationMiddleware.cs:line 39
         at Ocelot.Middleware.Multiplexer.Multiplexer.Fire(DownstreamContext context, OcelotRequestDelegate next) in D:\SnailProject\Ocelot\src\Ocelot\Middleware\Multiplexer\Multiplexer.cs:line 73
         at Ocelot.Middleware.Multiplexer.Multiplexer.Multiplex(DownstreamContext context, ReRoute reRoute, OcelotRequestDelegate next) in D:\SnailProject\Ocelot\src\Ocelot\Middleware\Multiplexer\Multiplexer.cs:line 33
         at Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\DownstreamRouteFinder\Middleware\DownstreamRouteFinderMiddleware.cs:line 57
         at Ocelot.Responder.Middleware.ResponderMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\Responder\Middleware\ResponderMiddleware.cs:line 34
         at Ocelot.Middleware.Pipeline.MapWhenMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\Middleware\Pipeline\MapWhenMiddleware.cs:line 40
         at Ocelot.Errors.Middleware.ExceptionHandlerMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\Errors\Middleware\ExceptionHandlerMiddleware.cs:line 54 RequestId: 0HLES1VH2VLE4:00000004, exception: System.InvalidOperationException: This instance has already started one or more requests. Properties can only be modified before sending the first request.
         at System.Net.Http.DelegatingHandler.CheckDisposedOrStarted()
         at System.Net.Http.DelegatingHandler.set_InnerHandler(HttpMessageHandler value)
         at Ocelot.Requester.HttpClientBuilder.<>c__DisplayClass13_0.<CreateHttpMessageHandler>b__1(Func`1 handler) in D:\SnailProject\Ocelot\src\Ocelot\Requester\HttpClientBuilder.cs:line 124
         at System.Collections.Generic.List`1.ForEach(Action`1 action)
         at Ocelot.Requester.HttpClientBuilder.CreateHttpMessageHandler(HttpMessageHandler httpMessageHandler, DownstreamReRoute request) in D:\SnailProject\Ocelot\src\Ocelot\Requester\HttpClientBuilder.cs:line 117
         at Ocelot.Requester.HttpClientBuilder.Create(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\Requester\HttpClientBuilder.cs:line 60
         at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\Requester\HttpClientHttpRequester.cs:line 31
         at Ocelot.Requester.Middleware.HttpRequesterMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\Requester\Middleware\HttpRequesterMiddleware.cs:line 23
         at Ocelot.Cache.Middleware.OutputCacheMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\Cache\Middleware\OutputCacheMiddleware.cs:line 33
         at Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\DownstreamUrlCreator\Middleware\DownstreamUrlCreatorMiddleware.cs:line 57
         at Ocelot.LoadBalancer.Middleware.LoadBalancingMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\LoadBalancer\Middleware\LoadBalancingMiddleware.cs:line 50
         at Ocelot.QueryStrings.Middleware.QueryStringBuilderMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\QueryStrings\Middleware\QueryStringBuilderMiddleware.cs:line 42
         at Ocelot.Headers.Middleware.HttpRequestHeadersBuilderMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\Headers\Middleware\HttpRequestHeadersBuilderMiddleware.cs:line 44
         at Ocelot.Authorisation.Middleware.AuthorisationMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\Authorisation\Middleware\AuthorisationMiddleware.cs:line 86
         at Ocelot.Claims.Middleware.ClaimsBuilderMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\Claims\Middleware\ClaimsBuilderMiddleware.cs:line 42
         at Ocelot.Authentication.Middleware.AuthenticationMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\Authentication\Middleware\AuthenticationMiddleware.cs:line 52
         at Ocelot.RequestId.Middleware.ReRouteRequestIdMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\RequestId\Middleware\ReRouteRequestIdMiddleware.cs:line 30
         at Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\RateLimit\Middleware\ClientRateLimitMiddleware.cs:line 38
         at Ocelot.Request.Middleware.DownstreamRequestInitialiserMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\Request\Middleware\DownstreamRequestInitialiserMiddleware.cs:line 39
         at Ocelot.Headers.Middleware.HttpHeadersTransformationMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\Headers\Middleware\HttpHeadersTransformationMiddleware.cs:line 39
         at Ocelot.Middleware.Multiplexer.Multiplexer.Fire(DownstreamContext context, OcelotRequestDelegate next) in D:\SnailProject\Ocelot\src\Ocelot\Middleware\Multiplexer\Multiplexer.cs:line 73
         at Ocelot.Middleware.Multiplexer.Multiplexer.Multiplex(DownstreamContext context, ReRoute reRoute, OcelotRequestDelegate next) in D:\SnailProject\Ocelot\src\Ocelot\Middleware\Multiplexer\Multiplexer.cs:line 33
         at Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\DownstreamRouteFinder\Middleware\DownstreamRouteFinderMiddleware.cs:line 57
         at Ocelot.Responder.Middleware.ResponderMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\Responder\Middleware\ResponderMiddleware.cs:line 34
         at Ocelot.Middleware.Pipeline.MapWhenMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\Middleware\Pipeline\MapWhenMiddleware.cs:line 40
         at Ocelot.Errors.Middleware.ExceptionHandlerMiddleware.Invoke(DownstreamContext context) in D:\SnailProject\Ocelot\src\Ocelot\Errors\Middleware\ExceptionHandlerMiddleware.cs:line 54
info: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
```

## Specifications

  - Version:7.0.6
  - Platform:
  - Subsystem:

**Comment by TomPallister** [comment]
@SnailDev please can you share your Startup.cs / Program.cs / ocelot.json so I can look into this further? Thanks :D

**Comment by SnailDev** [comment]
@TomPallister  I have create a test project https://github.com/OcelotStudy/OcelotTests which you could clone and run. just request http://localhost:5000/api001/values more times, the exception will occur.
and by the way , the doc about deleagating handler , handers may should be handlers.

![image](https://user-images.githubusercontent.com/30819423/42010464-4d5e877e-7ac1-11e8-83f1-d8ee3c87c7fa.png)

**Comment by TomPallister** [comment]
@SnailDev awesome I’ll take a look! Yes the spelling is wrong :(

**Comment by TomPallister** [comment]
@SnailDev I cannot get your example to work, it is configured to call API001 on http but the service calls app.UseHttpsRedirection(); so all traffic needs to be https! Should I just remove this?

**Comment by blackcoral88** [comment]
It seems to happen when HttpClientBuilder create a new httpclient. The same HttpMessageHandler cannot set InnerHandler when it is running by another httpclient. It should be a bug here. So you can just use AddTransientDelegatingHandler instead of AddSingletonDelegatingHandler
![_20180706164955](https://user-images.githubusercontent.com/16820933/42369456-9cee96b8-813c-11e8-94bb-01b43f6db1a2.png)

**Comment by TomPallister** [comment]
@blackcoral88 I think you are correct, I guess you cannot have singleton handlers ;) Whoooops!!

@SnailDev I think I will just have to remove this API! But I will look into it more closely ASAP.

**Comment by TomPallister** [comment]
Just released 7.0.9 to GitHub which removes delegating handlers. I’ve messed up semver because it should have been a breaking change. Will fix next release.

**Comment by beachwalker** [comment]
... unable to get DelegationHandlers to work. Does this feature still exist?

**Comment by thangchung** [comment]
@beachwalker I have got the same issue. The DelegationHandlers could not work, I did the same with the documentation suggested, but no luck

**Comment by MartinAaron** [comment]
> It seems to happen when HttpClientBuilder create a new httpclient. The same HttpMessageHandler cannot set InnerHandler when it is running by another httpclient. It might be a bug here. So you can just use AddTransientDelegatingHandler instead of AddSingletonDelegatingHandler ![_20180706164955](https://user-images.githubusercontent.com/16820933/42369456-9cee96b8-813c-11e8-94bb-01b43f6db1a2.png)

thx for the answer . I got same problem with inject grpc client.
