### ISSUE TITLE
HttpRequesterMiddleware error!

### ISSUE THREAD

**Issue by zjlhope** [ThreeMammals/Ocelot#494]
8001 is my api service,8000 is the gateway.when the route fit,the application has an error and process exit,I have found the error in code:
try
            {
                var response = await 
                httpClient.SendAsync(context.DownstreamRequest.ToHttpRequestMessage());
                return new OkResponse<HttpResponseMessage>(response);
            }

the error is following,why?

info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:8000/test/001
info: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
      requestId: 0HLFHCL59FUU9:00000001, previousRequestId: no previous request                                                                                                                 id, message: EndpointRateLimiting is not enabled for /api/values
info: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 0HLFHCL59FUU9:00000001, previousRequestId: no previous request                                                                                                                 id, message: No authentication needed for /test/001
info: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0]
      requestId: 0HLFHCL59FUU9:00000001, previousRequestId: no previous request                                                                                                                 id, message: /api/values route does not require user to be authorised
warn: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HLFHCL59FUU9:00000001, previousRequestId: no previous request                                                                                                                 id, message: Error making http request, exception: System.Net.Http.HttpRequestEx                                                                                                                ception: An error occurred while sending the request. ---> System.Net.Http.WinHt                                                                                                                tpException: ▒▒▒▒▒▒▒▒
         at System.Net.Http.WinHttpException.ThrowExceptionUsingLastError()
         at System.Net.Http.WinHttpHandler.InternalSendRequestAsync(WinHttpReque                                                                                                                stState state)
         at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
         --- End of inner exception stack trace ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebug                                                                                                                gerNotification(Task task)
         at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.Configured                                                                                                                TaskAwaiter.GetResult()
         at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
      --- End of stack trace from previous location where exception was thrown -                                                                                                                --
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebug                                                                                                                gerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at Ocelot.Requester.HttpClientHttpRequester.<GetResponse>d__4.MoveNext(                                                                                                                )

**Comment by TomPallister** [comment]
@zjlhope do you know what URL Oceot is trying to call? Is the service available?

Could you share your program.cs / startup.cs and json configuration?

**Comment by zjlhope** [comment]
ocelot is trying to call /api/values and this service is ok.
when call the http://localhost:8000/test/001,then can be reRouted to http://localhost:8001/api/values
from above logs,you can see ocelot acturally find the downstream path correctlly

**Comment by zjlhope** [comment]
{
    "ReRoutes": [
        {
            "UpstreamPathTemplate": "/test/001",
            "UpstreamHttpMethod": [
                "Get"
            ],
            "DownstreamPathTemplate": "/api/values",
            "DownstreamScheme": "http",
            "DownstreamHostAndPorts": [
                {
                    "Host": "localhost",
                    "Port": 8001
                }
            ],
        }
    ],
    "GlobalConfiguration": {
        "BaseUrl": "http://localhost:8000"
    }
}

**Comment by TomPallister** [comment]
@zjlhope thanks I will take a look ASAP!

**Comment by TomPallister** [comment]
@zjlhope this configuration works fine for me, please can you share your program.cs and startup.cs?

**Comment by TomPallister** [comment]
Let me know if you want to reopen this!
