### ISSUE TITLE
Error when AddDelegatingHandler

### ISSUE THREAD

**Issue by tungphuong** [ThreeMammals/Ocelot#496]
Hi,

I want to add one handler to trace but it throws exception

warn: Ocelot.Responder.Middleware.ResponderMiddleware[0]
      => ConnectionId:0HLFHJV2SU5QA => RequestId:0HLFHJV2SU5QA:00000002 RequestPath:/api/r/userprofile/countries
      requestId: 0HLFHJV2SU5QA:00000002, previousRequestId: no previous request id, message: Error Code: UnableToCompleteRequestError Message: Error making http request, exception: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The parameter is incorrect
         at System.Net.Http.WinHttpException.ThrowExceptionUsingLastError()
         at System.Net.Http.WinHttpHandler.InternalSendRequestAsync(WinHttpRequestState state)
         at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
         --- End of inner exception stack trace ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
         at System.Net.Http.DiagnosticsHandler.<SendAsync>d__2.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
         at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

My code is similar your guide

services.AddOcelot()
        .AddDelegatingHandler<FakeHandler>(true);

 public class FakeHandler : DelegatingHandler
    {
        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            return base.SendAsync(request, cancellationToken);
        }
    }

Besides, could you please provide one sample to integrate to zipkin or Jeager?

Thansk,

**Comment by TomPallister** [comment]
@tungphuong does Ocelot work without the delegating handler? Can you share your program.cs / startup.cs and json configuration? Also what URL are you calling Ocelot on?

**Comment by TomPallister** [comment]
Let me know if you want to reopen this!
