### ISSUE TITLE
The format of the URI could not be determined

### ISSUE THREAD

**Issue by xiaotupansy** [ThreeMammals/Ocelot#500]
## Expected Behavior / New Feature
Ocelot can work as normal.

## Actual Behavior / Motivation for New Feature
Error:
```
Ocelot.Errors.Middleware.ExceptionHandlerMiddleware:Error: requestId: 0HLFIQHRG0T47:00000001, previousRequestId: no previous request id, message: Exception caught in global error handler, exception message: Invalid URI: The format of the URI could not be determined., exception stack:    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at System.UriBuilder.get_Uri()
   at Ocelot.Request.Middleware.DownstreamRequest.ToUri()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware.Invoke(DownstreamContext context)
   at Ocelot.LoadBalancer.Middleware.LoadBalancingMiddleware.Invoke(DownstreamContext context)
   at Ocelot.QueryStrings.Middleware.QueryStringBuilderMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Headers.Middleware.HttpRequestHeadersBuilderMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Authorisation.Middleware.AuthorisationMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Claims.Middleware.ClaimsBuilderMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Authentication.Middleware.AuthenticationMiddleware.Invoke(DownstreamContext context)
   at Ocelot.RequestId.Middleware.ReRouteRequestIdMiddleware.Invoke(DownstreamContext context)
   at Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Request.Middleware.DownstreamRequestInitialiserMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Headers.Middleware.HttpHeadersTransformationMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Middleware.Multiplexer.Multiplexer.Fire(DownstreamContext context, OcelotRequestDelegate next)
   at Ocelot.Middleware.Multiplexer.Multiplexer.Multiplex(DownstreamContext context, ReRoute reRoute, OcelotRequestDelegate next)
   at Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Responder.Middleware.ResponderMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Middleware.Pipeline.MapWhenMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Errors.Middleware.ExceptionHandlerMiddleware.Invoke(DownstreamContext context) RequestId: 0HLFIQHRG0T47:00000001, exception: System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at System.UriBuilder.get_Uri()
   at Ocelot.Request.Middleware.DownstreamRequest.ToUri()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware.Invoke(DownstreamContext context)
   at Ocelot.LoadBalancer.Middleware.LoadBalancingMiddleware.Invoke(DownstreamContext context)
   at Ocelot.QueryStrings.Middleware.QueryStringBuilderMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Headers.Middleware.HttpRequestHeadersBuilderMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Authorisation.Middleware.AuthorisationMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Claims.Middleware.ClaimsBuilderMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Authentication.Middleware.AuthenticationMiddleware.Invoke(DownstreamContext context)
   at Ocelot.RequestId.Middleware.ReRouteRequestIdMiddleware.Invoke(DownstreamContext context)
   at Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Request.Middleware.DownstreamRequestInitialiserMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Headers.Middleware.HttpHeadersTransformationMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Middleware.Multiplexer.Multiplexer.Fire(DownstreamContext context, OcelotRequestDelegate next)
   at Ocelot.Middleware.Multiplexer.Multiplexer.Multiplex(DownstreamContext context, ReRoute reRoute, OcelotRequestDelegate next)
   at Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Responder.Middleware.ResponderMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Middleware.Pipeline.MapWhenMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Errors.Middleware.ExceptionHandlerMiddleware.Invoke(DownstreamContext context)
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 504.5287ms 500 
```

## Steps to Reproduce the Problem

  1.create consul using docker:
 first one server246:

```
docker run -d -p 8300:8300  -p 8301:8301/tcp -p 8301:8301/udp -p 8302:8302/tcp -p 8302:8302/udp -p 8400:8400 -p 8500:8500 -p 8600:8600 --name node246 --restart always -e 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}' consul agent -server -ui -client 0.0.0.0 -node=node246 -bootstrap-expect=1 -advertise 192.168.1.246
firewall-cmd --zone=public --add-port=8300/tcp --permanent
firewall-cmd --zone=public --add-port=8301/tcp --permanent
firewall-cmd --zone=public --add-port=8301/udp --permanent
firewall-cmd --zone=public --add-port=8302/tcp --permanent
firewall-cmd --zone=public --add-port=8302/udp --permanent
firewall-cmd --zone=public --add-port=8400/tcp --permanent
firewall-cmd --zone=public --add-port=8500/tcp --permanent
firewall-cmd --zone=public --add-port=8600/tcp --permanent
firewall-cmd --reload

```

second one server46:

```
docker run -d -p 8300:8300  -p 8301:8301/tcp -p 8301:8301/udp -p 8302:8302/tcp -p 8302:8302/udp -p 8400:8400 -p 8500:8500 -p 8600:8600 --name node46 --restart always -e 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}' consul agent -server -ui -client 0.0.0.0 -node=node46 -join 192.168.1.246 -advertise 192.168.1.46
firewall-cmd --zone=public --add-port=8300/tcp --permanent
firewall-cmd --zone=public --add-port=8301/tcp --permanent
firewall-cmd --zone=public --add-port=8301/udp --permanent
firewall-cmd --zone=public --add-port=8302/tcp --permanent
firewall-cmd --zone=public --add-port=8302/udp --permanent
firewall-cmd --zone=public --add-port=8400/tcp --permanent
firewall-cmd --zone=public --add-port=8500/tcp --permanent
firewall-cmd --zone=public --add-port=8600/tcp --permanent
firewall-cmd --reload

```
  2. to register docker image as service automatically to consul using registrator
first one server246:
`docker run -d -v /var/run/docker.sock:/tmp/docker.sock --name registrator -h registrator gliderlabs/registrator:latest -deregister="always" -internal=false consul://192.168.1.246:8500`

second one server46:
`docker run -d -v /var/run/docker.sock:/tmp/docker.sock --name registrator -h registrator gliderlabs/registrator:latest -deregister="always" -internal=false consul://192.168.1.46:8500`
  
3.settings for ocelot:
```
{
  "ReRoutes": [
    {
      "ReRouteIsCaseSensitive": true,
      "DownstreamPathTemplate": "/{url}",
      "UpstreamPathTemplate": "/{url}",
      "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete", "Options" ],
      "ServiceName": "webapi",
      "LoadBalancer": "RoundRobin",
      "RateLimitOptions": {
        "ClientWhitelist": [],
        "EnableRateLimiting": true,
        "Period": "1s",
        "PeriodTimespan": 1,
        "Limit": 3
      },
      "UseServiceDiscovery": true,
      "QoSOptions": {
        "ExceptionsAllowedBeforeBreaking": 3,
        "DurationOfBreak": 10,
        "TimeoutValue": 5000
      }
    }
  ],
  "GlobalConfiguration": {
    "RequestIdKey": "OcRequestId",
    "ServiceDiscoveryProvider": {
      "Host": "192.168.1.246",
      "Port": 8500
    }
  }
}

```

4. consul response for service webapi:
query addr:
http://192.168.1.246:8500/v1/health/service/webapi

response:
`[{"Node":{"ID":"72764c24-e026-899c-7cc9-02b31e341747","Node":"node246","Address":"192.168.1.246","Datacenter":"dc1","TaggedAddresses":{"lan":"192.168.1.246","wan":"192.168.1.246"},"Meta":{"consul-network-segment":""},"CreateIndex":5,"ModifyIndex":6},"Service":{"ID":"registrator:webapi:80","Service":"webapi","Tags":[],"Address":"","Meta":null,"Port":8189,"EnableTagOverride":false,"ProxyDestination":"","Connect":{"Native":false,"Proxy":null},"CreateIndex":14,"ModifyIndex":14},"Checks":[{"Node":"node246","CheckID":"serfHealth","Name":"Serf Health Status","Status":"passing","Notes":"","Output":"Agent alive and reachable","ServiceID":"","ServiceName":"","ServiceTags":[],"Definition":{},"CreateIndex":5,"ModifyIndex":5}]},{"Node":{"ID":"08d15763-2002-acff-7590-69e5d3d7f95b","Node":"node46","Address":"192.168.1.46","Datacenter":"dc1","TaggedAddresses":{"lan":"192.168.1.46","wan":"192.168.1.46"},"Meta":{"consul-network-segment":""},"CreateIndex":35,"ModifyIndex":36},"Service":{"ID":"registrator:webapi:80","Service":"webapi","Tags":[],"Address":"","Meta":null,"Port":8189,"EnableTagOverride":false,"ProxyDestination":"","Connect":{"Native":false,"Proxy":null},"CreateIndex":50,"ModifyIndex":50},"Checks":[{"Node":"node46","CheckID":"serfHealth","Name":"Serf Health Status","Status":"passing","Notes":"","Output":"Agent alive and reachable","ServiceID":"","ServiceName":"","ServiceTags":[],"Definition":{},"CreateIndex":35,"ModifyIndex":35}]}]`

## Specifications

  - Version:8.0.2   7.0.9
  - Platform:windows 7
  - Subsystem:.net core 2.1.301

**Comment by xiaotupansy** [comment]
When I have only one node in consul, Ocelot works.
But after register server46 into consul, Ocelot shows error.

**Comment by TomPallister** [comment]
@xiaotupansy that is very strange. I will take a look asap!

**Comment by TomPallister** [comment]
@xiaotupansy which version of Ocelot are you trying to use? I suggest latest which is 8.0.3 and see if this works. The reason I say that is the stacktrace you have pasted doesnt seem to be possible with current Ocleot so it might be an old version with a bug.

**Comment by xiaotupansy** [comment]
@TomPallister tested with 8.0.2 and 7.0.9.

**Comment by xiaotupansy** [comment]
Here are all my code:

Startup.cs
`using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Cors.Internal;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Ocelot.DependencyInjection;
using Ocelot.Middleware;

namespace OcelotExample
{
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
            services.AddCors(options =>
            {
                options.AddPolicy("AllowSpecificOrigin",
                    builder => builder.WithOrigins("*").AllowAnyMethod().AllowAnyHeader());

            });
            services.Configure<MvcOptions>(options =>
            {
                options.Filters.Add(new CorsAuthorizationFilterFactory("AllowSpecificOrigin"));
            });
            services.AddOcelot(new ConfigurationBuilder().AddJsonFile("ocelot.json").Build());
        }

        public async void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.UseMvc();
            app.UseCors("AllowSpecificOrigin");
            await app.UseOcelot();

        }
    }
}
`

Program.cs
`using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;

namespace OcelotExample
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
    }
}
`

ocelot.json

`{
  "ReRoutes": [
    {
      "ReRouteIsCaseSensitive": true,
      "DownstreamPathTemplate": "/{url}",
      "UpstreamPathTemplate": "/{url}",
      "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete", "Options" ],
      "ServiceName": "webapi",
      "LoadBalancer": "RoundRobin",
      "RateLimitOptions": {
        "ClientWhitelist": [],
        "EnableRateLimiting": true,
        "Period": "1s",
        "PeriodTimespan": 1,
        "Limit": 3
      },
      "UseServiceDiscovery": true,
      "QoSOptions": {
        "ExceptionsAllowedBeforeBreaking": 3,
        "DurationOfBreak": 10,
        "TimeoutValue": 5000
      }
    }
  ],
  "GlobalConfiguration": {
    "RequestIdKey": "OcRequestId",
    "ServiceDiscoveryProvider": {
      "Host": "192.168.1.246",
      "Port": 8500
    }
  }
}
`

**Comment by TomPallister** [comment]
@xiaotupansy after looking more closely at your services in consul

```json
"Service": {
            "ID": "registrator:webapi:80",
            "Service": "webapi",
            "Tags": [],
            "Address": "",
            "Meta": null,
            "Port": 8189,
            "EnableTagOverride": false,
            "ProxyDestination": "",
            "Connect": {
                "Native": false,
                "Proxy": null
            },
            "CreateIndex": 14,
            "ModifyIndex": 14
        }
```
and 

```json
  "Service": {
            "ID": "registrator:webapi:80",
            "Service": "webapi",
            "Tags": [],
            "Address": "",
            "Meta": null,
            "Port": 8189,
            "EnableTagOverride": false,
            "ProxyDestination": "",
            "Connect": {
                "Native": false,
                "Proxy": null
            },
            "CreateIndex": 50,
            "ModifyIndex": 50
        },
```

You can see they do not have an address so Ocelot is unable to call them. I will make a change to Ocelot so that this error is logged and Ocelot will not try to use the service.

**Comment by xiaotupansy** [comment]
@TomPallister After some research work, I change consul output to the following:
```[{"ID":"963985de-1f8d-9bdf-a488-b41b46ee2de5","Node":"node246","Address":"192.168.1.246","Datacenter":"dc1","TaggedAddresses":{"lan":"192.168.1.246","wan":"192.168.1.246"},"NodeMeta":{"consul-network-segment":""},"ServiceKind":"","ServiceID":"registrator:webapi:80","ServiceName":"webapi","ServiceTags":[],"ServiceAddress":"192.168.1.246","ServiceMeta":{},"ServicePort":8189,"ServiceEnableTagOverride":false,"ServiceProxyDestination":"","ServiceConnect":{"Native":false,"Proxy":null},"CreateIndex":16,"ModifyIndex":16},{"ID":"e6bdc1f4-9eb3-8556-b661-4207b364ce9a","Node":"node46","Address":"192.168.1.46","Datacenter":"dc1","TaggedAddresses":{"lan":"192.168.1.46","wan":"192.168.1.46"},"NodeMeta":{"consul-network-segment":""},"ServiceKind":"","ServiceID":"registrator:webapi:80","ServiceName":"webapi","ServiceTags":[],"ServiceAddress":"192.168.1.46","ServiceMeta":{},"ServicePort":8189,"ServiceEnableTagOverride":false,"ServiceProxyDestination":"","ServiceConnect":{"Native":false,"Proxy":null},"CreateIndex":53,"ModifyIndex":53}]```

You can see that ServiceAddress is correct now.
But I still get the same error.
After pull all Ocelot code to local and debug, I find that it's caused by null reference to Schema:

```public string ToUri()
        {
            var uriBuilder = new UriBuilder
            {
                Port = Port,
                Host = Host,
                Path = AbsolutePath,
                Query = Query,
                Scheme = Scheme
            };

            return uriBuilder.Uri.AbsoluteUri;
        }```

**Comment by TomPallister** [comment]
You need to set the scheme as per the documentation! Does it work now you set the scheme? If not please upload all of your code so I can check!

**Comment by xiaotupansy** [comment]
Yes it can work now.
I found that original version of ocelot generates a development version of ocelot.json (my configuration file) -->ocelot.development.json.
It fails new configuration and makes ocelot always using the original version of configuration.

**Comment by TomPallister** [comment]
Ok good that it is working!
