### ISSUE TITLE
线上环境并发大httpclient提交到下游服务偶尔报错

### ISSUE THREAD

**Issue by 511568420** [ThreeMammals/Ocelot#557]
报错的代码： Ocelot.Requester.HttpClientHttpRequester  类中
var response = await httpClient.SendAsync(context.DownstreamRequest.ToHttpRequestMessage())

错误信息：Ocelot.Responder.Middleware.ResponderMiddleware|ERROR|requestId: no request id, previousRequestId: no previous request id, message: Error making http request, exception: System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: The read operation failed, see inner exception. ---> System.Net.Http.CurlException: Transferred a partial file
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.NoWriteNoSeekStreamContent.<>c.<SerializeToStreamAsync>b__4_0(Task t, Object s)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__48.MoveNext()
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ocelot.Requester.HttpClientHttpRequester.<GetResponse>d__4.MoveNext()

**Comment by TomPallister** [comment]
@511568420 thanks for your interest in the project. Can you confirm this error happens when Ocelot is under heavy load?

google translate : Online environment concurrent large httpclient submitted to downstream service occasionally error

**Comment by 511568420** [comment]
@TomPallister    The Ocelot cluster is deployed in the Linux environment, using Docker deployment, and the downstream service cluster is also deployed in the Linux environment using Docker. Now each Ocelot service has a failure rate of 0.8% to 1% per hour to access the downstream service. However, millions of visits to the test environment are normal, except that the test environment is deployed on the same machine. On the device, the formal environment is in the same LAN, but not the same IP.
