### ISSUE TITLE
Chinese is not decoded correctly in query string

### ISSUE THREAD

**Issue by Varorbc** [ThreeMammals/Ocelot#567]
## Steps to Reproduce the Problem

  1.test?abc=无牌车
  2.test?abc=\xC3\xA6\xC2\x97\xC2\xA0\xC3\xA8\xC2\xBD\xC2\xA6\xC3\xA7\xC2\x89\xC2\x8C

**Comment by TomPallister** [comment]
@Varorbc thanks for this I will take a look. I don't think I do anything to break this but obviously do!

**Comment by Varorbc** [comment]
@TomPallister thanks
 
# log:

2018-08-21 17:21:33.657 +08:00 [INF] Connection id "0HLG77R7Q71PB" bad request data: "Invalid request target: '/test?abc=\xC3\xA6\xC2\x97\xC2\xA0\xC3\xA8\xC2\xBD\xC2\xA6\xC3\xA7\xC2\x89\xC2\x8C'"
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Invalid request target: '/test?abc=\xC3\xA6\xC2\x97\xC2\xA0\xC3\xA8\xC2\xBD\xC2\xA6\xC3\xA7\xC2\x89\xC2\x8C'
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowRequestTargetRejected(Span`1 target)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.OnOriginFormTarget(HttpMethod method, HttpVersion version, Span`1 target, Span`1 path, Span`1 query, Span`1 customMethod, Boolean pathEncoded)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.OnStartLine(HttpMethod method, HttpVersion version, Span`1 target, Span`1 path, Span`1 query, Span`1 customMethod, Boolean pathEncoded)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, Byte* data, Int32 length)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.IHttpParser<TRequestHandler>.ParseRequestLine(TRequestHandler handler, ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TakeStartLine(ReadOnlySequence`1 buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.ParseRequest(ReadOnlySequence`1 buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TryParseRequest(ReadResult result, Boolean& endConnection)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)

**Comment by Varorbc** [comment]
https://github.com/aspnet/KestrelHttpServer/issues/2842

**Comment by Varorbc** [comment]
https://github.com/aspnet/KestrelHttpServer/issues/1144

**Comment by TomPallister** [comment]
Thanks for the update!
