### ISSUE TITLE
Ocelot.Errors.Middleware.ExceptionHandlerMiddleware

### ISSUE THREAD

**Issue by winlj** [ThreeMammals/Ocelot#573]
fail: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      requestId: 0HLG9IP6SGU2K:00000004, previousRequestId: no previous request id, message: Exception caught in global error handler, exception message: Object reference not set to an instance of an object., exception stack:    at Ocelot.LoadBalancer.LoadBalancers.LoadBalancerFactory.<>c__DisplayClass2_0.<<Get>b__0>d.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Ocelot.LoadBalancer.LoadBalancers.RoundRobin.Lease(DownstreamContext downstreamContext)
         at Ocelot.LoadBalancer.Middleware.LoadBalancingMiddleware.Invoke(DownstreamContext context)
         at Ocelot.QueryStrings.Middleware.QueryStringBuilderMiddleware.Invoke(DownstreamContext context)
         at Ocelot.Headers.Middleware.HttpRequestHeadersBuilderMiddleware.Invoke(DownstreamContext context)
         at Ocelot.Authorisation.Middleware.AuthorisationMiddleware.Invoke(DownstreamContext context)
         at Ocelot.Claims.Middleware.ClaimsBuilderMiddleware.Invoke(DownstreamContext context)
         at Ocelot.Authentication.Middleware.AuthenticationMiddleware.Invoke(DownstreamContext context)
         at Ocelot.RequestId.Middleware.ReRouteRequestIdMiddleware.Invoke(DownstreamContext context)
         at Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware.Invoke(DownstreamContext context)
         at Ocelot.Request.Middleware.DownstreamRequestInitialiserMiddleware.Invoke(DownstreamContext context)
         at Ocelot.Headers.Middleware.HttpHeadersTransformationMiddleware.Invoke(DownstreamContext context)
         at Ocelot.Middleware.Multiplexer.Multiplexer.Fire(DownstreamContext context, OcelotRequestDelegate next)
         at Ocelot.Middleware.Multiplexer.Multiplexer.Multiplex(DownstreamContext context, ReRoute reRoute, OcelotRequestDelegate next)
         at Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware.Invoke(DownstreamContext context)
         at Ocelot.Responder.Middleware.ResponderMiddleware.Invoke(DownstreamContext context)
         at Ocelot.Middleware.Pipeline.MapWhenMiddleware.Invoke(DownstreamContext context)
         at Ocelot.Errors.Middleware.ExceptionHandlerMiddleware.Invoke(DownstreamContext context) RequestId: 0HLG9IP6SGU2K:00000004, exception: System.NullReferenceException: Object reference not set to an instance of an object.
         at Ocelot.LoadBalancer.LoadBalancers.LoadBalancerFactory.<>c__DisplayClass2_0.<<Get>b__0>d.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Ocelot.LoadBalancer.LoadBalancers.RoundRobin.Lease(DownstreamContext downstreamContext)
         at Ocelot.LoadBalancer.Middleware.LoadBalancingMiddleware.Invoke(DownstreamContext context)
         at Ocelot.QueryStrings.Middleware.QueryStringBuilderMiddleware.Invoke(DownstreamContext context)
         at Ocelot.Headers.Middleware.HttpRequestHeadersBuilderMiddleware.Invoke(DownstreamContext context)
         at Ocelot.Authorisation.Middleware.AuthorisationMiddleware.Invoke(DownstreamContext context)
         at Ocelot.Claims.Middleware.ClaimsBuilderMiddleware.Invoke(DownstreamContext context)
         at Ocelot.Authentication.Middleware.AuthenticationMiddleware.Invoke(DownstreamContext context)
         at Ocelot.RequestId.Middleware.ReRouteRequestIdMiddleware.Invoke(DownstreamContext context)
         at Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware.Invoke(DownstreamContext context)
         at Ocelot.Request.Middleware.DownstreamRequestInitialiserMiddleware.Invoke(DownstreamContext context)
         at Ocelot.Headers.Middleware.HttpHeadersTransformationMiddleware.Invoke(DownstreamContext context)
         at Ocelot.Middleware.Multiplexer.Multiplexer.Fire(DownstreamContext context, OcelotRequestDelegate next)
         at Ocelot.Middleware.Multiplexer.Multiplexer.Multiplex(DownstreamContext context, ReRoute reRoute, OcelotRequestDelegate next)
         at Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware.Invoke(DownstreamContext context)
         at Ocelot.Responder.Middleware.ResponderMiddleware.Invoke(DownstreamContext context)
         at Ocelot.Middleware.Pipeline.MapWhenMiddleware.Invoke(DownstreamContext context)
         at Ocelot.Errors.Middleware.ExceptionHandlerMiddleware.Invoke(DownstreamContext context)

=====================================
{
  "ReRoutes": [
    { //swagger route
      "UseServiceDiscovery": true,
      "DownstreamPathTemplate": "/swagger/v1/swagger.json",
      "DownstreamScheme": "http",
      "ServiceName": "SwaggerService",
      "LoadBalancer": "RoundRobin",
      "UpstreamPathTemplate": "/doc/apiv1/swagger.json",
      "UpstreamHttpMethod": [ "GET", "POST", "DELETE", "PUT" ]
    },
    { //test route
      "UseServiceDiscovery": true,
      "DownstreamPathTemplate": "/{url}",
      "DownstreamScheme": "http",
      "ServiceName": "TestService",
      "LoadBalancerOptions": {
        "Type": "RoundRobin"
      },
      "UpstreamPathTemplate": "/test/{url}",
      "UpstreamHttpMethod": [ "GET", "POST" ],
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "usergateway",
        "AllowScopes": [ "api1" ]
      }
    },
    { //organization route
      "UseServiceDiscovery": true,
      "DownstreamPathTemplate": "/org/api/test",
      "DownstreamScheme": "http",
      "ServiceName": "OrganizationService",
      "LoadBalancerOptions": {
        "Type": "RoundRobin"
      },
      "UpstreamPathTemplate": "/org/api/test",
      "UpstreamHttpMethod": [ "GET", "POST" ],
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "usergateway",
        "AllowScopes": [ "api1" ]
      }
    },
    { //universaldata route
      "UseServiceDiscovery": true,
      "DownstreamPathTemplate": "/universal/area/api/{url}",
      "DownstreamScheme": "http",
      "ServiceName": "UniversalDataService",
      "LoadBalancerOptions": {
        "Type": "RoundRobin"
      },
      "UpstreamPathTemplate": "/universal/{url}",
      "UpstreamHttpMethod": [ "GET", "POST" ],
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "usergateway",
        "AllowScopes": [ "api1" ]
      }
    },
    { //team route
      "UseServiceDiscovery": true,
      "DownstreamPathTemplate": "/team/api/{url}",
      "DownstreamScheme": "http",
      "ServiceName": "TeamService",
      "LoadBalancerOptions": {
        "Type": "RoundRobin"
      },
      "UpstreamPathTemplate": "/team/{url}",
      "UpstreamHttpMethod": [ "GET", "POST" ],
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "usergateway",
        "AllowScopes": [ "api1" ]
      }
    }
  ],
  "GlobalConfiguration": {
    "ServiceDiscoveryProvider": {
      "Host": "consulservice",
      "Port": 8500
    }
  },
  "QosOptions": {
    "ExceptionsAllowedBeforeBreaking": 3,
    "DurationOfBreak": 5,
    "TimeoutValue": 5000
  }
}

**Comment by TomPallister** [comment]
@winlj please can you share the json from consul when you request the services e.g. consulservice:8500/v1/health/service/{serviceName}

**Comment by winlj** [comment]
use  ID4   jwt  token

**Comment by winlj** [comment]
use  postman
content：
Authorization:Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjljMTIzOTM2MmE1ZTllMDNkMGQ0OGNlZmYwNGQyYzQwIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1MzUzNDkxNDYsImV4cCI6MTUzNTM4NTE0NiwiaXNzIjoiaHR0cDovL29hdXRoc2VydmljZTo2MDEzIiwiYXVkIjpbImh0dHA6Ly9vYXV0aHNlcnZpY2U6NjAxMy9yZXNvdXJjZXMiLCJhcGkxIl0sImNsaWVudF9pZCI6IkpRUHJvamVjdC5PcmcuV2ViQVBJIiwic3ViIjoibGlqaWFuIiwiYXV0aF90aW1lIjoxNTM1MzQ5MTQ2LCJpZHAiOiJsb2NhbCIsInJlc3VsdCI6IntcIklEXCI6NzEsXCJVc2VyQ29kZVwiOlwibGlqaWFuXCIsXCJVc2VyVHlwZVwiOjEsXCJTZXhcIjoxLFwiRW1haWxcIjpcIjY0NjUyNTRAcXEuY29tXCIsXCJNb2JpbGVcIjpcIjE1NjQyOTQ3Nzc4XCIsXCJOYW1lXCI6XCLmnY7lgaVcIixcIlJvbGVzXCI6bnVsbH0iLCJzY29wZSI6WyJhcGkxIl0sImFtciI6WyJsaWppYW4iXX0.boogo6wN70Gbffe5fF_xAIlVFWq7LCzwJNWAtzJj1tpAYY1UvgoeHk7cTnMQdmcDameZjvqX1xUrlcTEphc7D_prZaGOySf9etADTIJBTheZLN78QXPbzEdRh8MaXEqCXa4Lem4XVWxshTZByfDl5Fa_f-9FTJbQsRSJ6LhzPy-MZKthGombIrCJUJVi1UwaT3cTO_V_8995Pp7YURYBmup7Mczcv5WqJH6LgNfIYyIR78Ot-BL-c-EUN3heM5SX1UDGlgWo5ux2I3BuIKKuPFEMdR5CGbpBFZNXu4J7OPcFJfIgIuZwncTH50qpx-AA64UptfmHYlXycMQKiYGt5A

**Comment by winlj** [comment]
2018/08/27 07:03:55 [INFO] serf: EventMemberJoin: consulservice 172.18.0.2
    2018/08/27 07:03:55 [INFO] serf: EventMemberJoin: consulservice.dc1 172.18.0.2
    2018/08/27 07:03:55 [INFO] raft: Node at 172.18.0.2:8300 [Follower] entering Follower state
    2018/08/27 07:03:55 [INFO] consul: adding server consulservice (Addr: 172.18.0.2:8300) (DC: dc1)
    2018/08/27 07:03:55 [INFO] consul: adding server consulservice.dc1 (Addr: 172.18.0.2:8300) (DC: dc1)
    2018/08/27 07:03:55 [ERR] agent: failed to sync remote state: No cluster leader
    2018/08/27 07:03:56 [WARN] raft: Heartbeat timeout reached, starting election
    2018/08/27 07:03:56 [INFO] raft: Node at 172.18.0.2:8300 [Candidate] entering Candidate state
    2018/08/27 07:03:56 [INFO] raft: Election won. Tally: 1
    2018/08/27 07:03:56 [INFO] raft: Node at 172.18.0.2:8300 [Leader] entering Leader state
    2018/08/27 07:03:56 [INFO] consul: cluster leadership acquired
    2018/08/27 07:03:56 [INFO] consul: New leader elected: consulservice
    2018/08/27 07:03:56 [INFO] raft: Disabling EnableSingleNode (bootstrap)
    2018/08/27 07:03:56 [INFO] consul: member 'consulservice' joined, marking health alive
    2018/08/27 07:03:56 [INFO] agent: Synced service 'consul'
    2018/08/27 07:04:07 [WARN] Service tag "urlprefix-/OrganizationService" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
    2018/08/27 07:04:07 [INFO] agent: Synced service '778b3ab9-60c0-42f3-a538-4136407892e5'
    2018/08/27 07:04:13 [WARN] Service tag "urlprefix-/OAuthService" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
    2018/08/27 07:04:13 [INFO] agent: Synced service '41f328cb-c7ae-4b69-90b8-de423eaa3457'
    2018/08/27 07:04:16 [INFO] agent: Synced check 'service:778b3ab9-60c0-42f3-a538-4136407892e5'
    2018/08/27 07:04:23 [WARN] Service tag "urlprefix-/TokenService" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
    2018/08/27 07:04:23 [INFO] agent: Synced service '65ce2b47-5369-461f-982c-e0d2fa04fbc7'
    2018/08/27 07:04:23 [INFO] agent: Synced check 'service:41f328cb-c7ae-4b69-90b8-de423eaa3457'
    2018/08/27 07:04:25 [INFO] agent: Synced check 'service:65ce2b47-5369-461f-982c-e0d2fa04fbc7'
    2018/08/27 07:05:07 [WARN] Service tag "urlprefix-/OcelotService" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
    2018/08/27 07:05:07 [INFO] agent: Synced service '54347e85-d74d-4fb8-8613-ea97b017f973'
    2018/08/27 07:05:17 [INFO] agent: Synced check 'service:54347e85-d74d-4fb8-8613-ea97b017f973'
    2018/08/27 07:12:04 [INFO] agent: Deregistered service '54347e85-d74d-4fb8-8613-ea97b017f973'
    2018/08/27 07:12:04 [INFO] agent: Deregistered check 'service:54347e85-d74d-4fb8-8613-ea97b017f973'
    2018/08/27 07:13:06 [WARN] Service tag "urlprefix-/OcelotService" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.
    2018/08/27 07:13:06 [INFO] agent: Synced service 'a97e3c62-00d7-46ad-8600-81917e18b965'
    2018/08/27 07:13:09 [INFO] agent: Synced check 'service:a97e3c62-00d7-46ad-8600-81917e18b965'

**Comment by TomPallister** [comment]
Also these docs might help 
https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html

**Comment by winlj** [comment]
ok  i try

**Comment by TomPallister** [comment]
Also do you have the Ocelot.Provider.Consul package referenced with AddConsul ?

**Comment by winlj** [comment]
yes，nuget-consul  --version--0.7.2.6

**Comment by winlj** [comment]
register：
public static IApplicationBuilder RegisterConsul(this IApplicationBuilder app, IApplicationLifetime lifetime, ServiceEntity serviceEntity)
        {
            var consulClient = new ConsulClient(x => x.Address = new Uri($"http://{serviceEntity.ConsulIP}:{serviceEntity.ConsulPort}"));//请求注册的 Consul 地址
            var httpCheck = new AgentServiceCheck()
            {
                DeregisterCriticalServiceAfter = TimeSpan.FromSeconds(5),//服务启动多久后注册
                Interval = TimeSpan.FromSeconds(10),//健康检查时间间隔，或者称为心跳间隔
                HTTP = $"http://{serviceEntity.IP}:{serviceEntity.Port}/api/health",//健康检查地址
                Timeout = TimeSpan.FromSeconds(5)
            };

            // Register service with consul
            var registration = new AgentServiceRegistration()
            {
                Checks = new[] { httpCheck },
                ID = Guid.NewGuid().ToString(),
                Name = serviceEntity.ServiceName,
                Address = serviceEntity.IP,
                Port = serviceEntity.Port,
                Tags = new[] { $"urlprefix-/{serviceEntity.ServiceName}" }//添加 urlprefix-/servicename 格式的 tag 标签，以便 Fabio 识别
            };

            consulClient.Agent.ServiceRegister(registration).Wait();//服务启动时注册，内部实现其实就是使用 Consul API 进行注册（HttpClient发起）
            lifetime.ApplicationStopping.Register(() =>
            {
                consulClient.Agent.ServiceDeregister(registration.ID).Wait();//服务停止时取消注册
            });

            return app;
        }
    }

**Comment by winlj** [comment]
as below is  good

    {
      "UseServiceDiscovery": false,
      "DownstreamPathTemplate": "/org/{url}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "organizationservice",
          "Port": "6001"
        }
      ],
      //"ServiceName": "OrganizationService",
      "LoadBalancerOptions": {
        "Type": "RoundRobin"
      },
      "UpstreamPathTemplate": "/org/{url}",
      "UpstreamHttpMethod": [ "GET", "POST" ],
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "usergateway",
        "AllowScopes": [ "api1" ]
      }
    },

**Comment by TomPallister** [comment]
@winlj I meant are you using this package https://github.com/ThreeMammals/Ocelot.Provider.Consul? If you are using a newer version of Ocelot you have to have this.

**Comment by winlj** [comment]
i use docker      ,--network

**Comment by winlj** [comment]
The problem is resolved,
I use the  --version 8.0.2  is ok
other version   is bad
I hope to find the reason, thank you

**Comment by TomPallister** [comment]
Ok cool, guess it was a bug fix!
