### ISSUE TITLE
ocelot in docker  refused to connect.

### ISSUE THREAD

**Issue by hongwei7458** [ThreeMammals/Ocelot#638]
## Expected Behavior / New Feature

hi @TomPallister ,   i have a problem, 
a gateway , and two services . 
gateway not work in docker , but it is work on my  computer. 
i do not   how to fix it. 
 docker logs -----
[dev@slave1 work]$ sudo docker logs gateway_2
Hosting environment: Production
Content root path: /app/
Now listening on: http://localhost:9000
Application started. Press Ctrl+C to shut down.
[dev@slave1 work]$ 
--------------
 coelot   config --------
`{
      "UpstreamPathTemplate": "/products",
      "UpstreamHttpMethod": [ "Get" ],
      "DownstreamPathTemplate": "/api/products",
      "DownstreamScheme": "http",
      //"DownstreamHost": "localhost",
      //"DownstreamPort": 9001,
      "DownstreamHostAndPorts": [
        {
         "Host": "localhost", //  on server i will change localhost   to server ip
          "Port": 8002
        },
        {
          "Host": "localhost",
          "Port": 8003
        }
      ],
      "LoadBalancerOptions": {
        "Type": "RoundRobin"
      },
      "Key": "Product"
    }`
-----------

docker container ------

PORTS                                                                NAMES
0.0.0.0:8008->80/tcp                                                 gateway_2
0.0.0.0:8000->80/tcp                                                 gateway_1
9002/tcp, 0.0.0.0:8003->80/tcp                                       products_2
9002/tcp, 0.0.0.0:8002->80/tcp                                       products_1
0.0.0.0:8001->80/tcp                                                 customer_1

products_1 and products_2  and customer_1 is  work , when i request   gateway_1 and gateway_2 
 do not work . 

-----
 
server : linux
ocelot version :11.03
.netcore:2.1

**Comment by hongwei7458** [comment]
i find the error .. 
` fail: Ocelot.Provider.Polly.PollyCircuitBreakingDelegatingHandler[0]
      requestId: 0HLH3IGILNL7I:00000001, previousRequestId: no previous request id, message: Error in CircuitBreakingDelegatingHandler.SendAync, exception: System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         at System.Threading.Tasks.ValueTask`1.get_Result()
         at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Threading.Tasks.ValueTask`1.get_Result()
         at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
         at System.Threading.Tasks.ValueTask`1.get_Result()
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
         at Polly.Policy.<>c__DisplayClass181_0`1.<<ExecuteAsyncInternal>b__0>d.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Polly.Policy.<>c__DisplayClass213_1.<<TimeoutAsync>b__1>d.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Polly.Timeout.TimeoutEngine.ImplementationAsync[TResult](Func`3 action, Context context, Func`2 timeoutProvider, TimeoutStrategy timeoutStrategy, Func`4 onTimeoutAsync, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
         at Polly.Timeout.TimeoutEngine.ImplementationAsync[TResult](Func`3 action, Context context, Func`2 timeoutProvider, TimeoutStrategy timeoutStrategy, Func`4 onTimeoutAsync, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
         at Polly.Policy.ExecuteAsyncInternal[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
         at Polly.Wrap.PolicyWrapEngine.<>c__DisplayClass8_0`1.<<ImplementationAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Polly.Policy.<>c__DisplayClass181_0`1.<<ExecuteAsyncInternal>b__0>d.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Polly.CircuitBreakerSyntaxAsync.<>c__DisplayClass5_1.<<CircuitBreakerAsync>b__2>d.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Polly.CircuitBreaker.CircuitBreakerEngine.ImplementationAsync[TResult](Func`3 action, Context context, IEnumerable`1 shouldHandleExceptionPredicates, IEnumerable`1 shouldHandleResultPredicates, ICircuitController`1 breakerController, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
         at Polly.Policy.ExecuteAsyncInternal[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
         at Polly.Wrap.PolicyWrapEngine.ImplementationAsync[TResult](Func`3 func, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, IAsyncPolicy outerPolicy, IAsyncPolicy innerPolicy)
         at Ocelot.Provider.Polly.PollyCircuitBreakingDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
warn: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
`

**Comment by carloslozano** [comment]
Hi,

My recommendation would be to run your APIs in named containers (with ```--name``` parameter);  
* ```docker run -d --name myapi1 my-api1-image```, and,
* ```docker run -d --name myapi2 my-api2-image```, etc.

Then run your ocelot with docker and link its container to the others (with ```--link```parameter;
* ```docker run -d -p 8080:5000 --link myapi1:myapi1 --link myapi2:myapi2 my-ocelot-image```

With this approach, **myapi1** and **myapi2** will become **hostnames** within the container and the container network they share, so you can use hostnames in your ocelot config file to route traffic to the correct service - also, no need to expose your APIs with -p on a public port, thus ensuring all traffic goes over the gateway.

From the information you've provided, it seems as though you're expecting ocelot to know how to connect to localhost on your host machine... when it's actually trying to connect to localhost in its container.

**Comment by hongwei7458** [comment]
@carloslozano  
thanks,  this is  all container .
my ocelot and services in one server
![qq 20180926193348](https://user-images.githubusercontent.com/31685551/46077316-03b86600-c1c3-11e8-888f-684e2df947c4.png)
  in my ocelot  configuration.json  host =localhost  or host =127.0.0.1 or host=server ip 
both not work..
 here is docker logs 
`Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HLH3K1N3CT5A:00000001, previousRequestId: no previous request id, message: Error making http request, exception: System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         at System.Threading.Tasks.ValueTask`1.get_Result()
         at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Threading.Tasks.ValueTask`1.get_Result()
         at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
         at System.Threading.Tasks.ValueTask`1.get_Result()
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
         at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context)
`

**Comment by hongwei7458** [comment]
i fix  error

**Comment by TomPallister** [comment]
Good work! Well done :)

**Comment by gfelot** [comment]
Hi @hongwei7458 and @TomPallister.

I have the same issue.

@carloslozano solution is not working and `--link` is deprecated.
So I decided to use a bridged network `--network`.

This is how I launch my 2 dotnet projects

`Mock Service` (for testing) :
`docker build -t apigateway.mock . && docker run --rm -p 5100:5100 --network apigateway-net --env ASPNETCORE_URLS=http://0.0.0.0:5100 --env ASPNETCORE_ENVIRONMENT=Development --name APIGateway.Mock apigateway.mock`

`APIGW-Ocelot`:
`docker build -t apigateway.base . && docker run --rm -p 5000:5000  --network apigateway-net --env ASPNETCORE_URLS=http://0.0.0.0:5000 --env ASPNETCORE_ENVIRONMENT=Development --name APIGateway.Base apigateway.base`

Then In another container I can ping both `ping APIGateway.Base` and `ping APIGateway.Mock`.
So I my `ReRoute` I used `APIGateway.Mock`for the URL like :

```
    {
      "UpstreamPathTemplate": "/api/organizations",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "APIGateway.Mock",
          "Port": 5100
        }
      ],
      "DownstreamPathTemplate": "/mock/organizations",
      "FileCacheOptions": { "TtlSeconds": 600, "Region": "organizations" }
    }
```
@hongwei7458 can you explain how did you manage to fix it ?

**Comment by akaramanapp** [comment]
@carloslozano thanks you. good job.
