### ISSUE TITLE
Websocket reroute fails

### ISSUE THREAD

**Issue by REPRESSION** [ThreeMammals/Ocelot#696]
## Expected Behavior / New Feature
Client should be able to connect to microservice with WS through Ocelot

## Actual Behavior / Motivation for New Feature
WS doesn't stays open, microservice gets a connection event on the websocket, but everything stops working after that point. Direct connection between client and microservice is working.

ocelot.json:
```
    {
      "UpstreamPathTemplate": "/videomanager/ws",
      "DownstreamPathTemplate": "/ws",
      "DownstreamScheme": "ws",
      "DownstreamHostAndPorts": [
        {
          "Host": "videomanager",
          "Port": "80"
        }
      ]
    },
```

server side logs :
```
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:4401/videomanager/ws

[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
Request starting HTTP/1.1 GET http://localhost:4401/videomanager/ws

[40m[37mdbug[39m[22m[49m: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
requestId: 0HLIHBR58KQ27:00000001, previousRequestId: no previous request id, message: ocelot pipeline started
Ocelot.Errors.Middleware.ExceptionHandlerMiddleware:Debug: requestId: 0HLIHBR58KQ27:00000001, previousRequestId: no previous request id, message: ocelot pipeline started
Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware:Debug: requestId: 0HLIHBR58KQ27:00000001, previousRequestId: no previous request id, message: Upstream url path is /videomanager/ws

[40m[37mdbug[39m[22m[49m: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
requestId: 0HLIHBR58KQ27:00000001, previousRequestId: no previous request id, message: Upstream url path is /videomanager/ws

[40m[37mdbug[39m[22m[49m: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
requestId: 0HLIHBR58KQ27:00000001, previousRequestId: no previous request id, message: downstream templates are /ws
Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware:Debug: requestId: 0HLIHBR58KQ27:00000001, previousRequestId: no previous request id, message: downstream templates are /ws
Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware:Information: requestId: 0HLIHBR58KQ27:00000001, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /ws

[40m[32minfo[39m[22m[49m: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
requestId: 0HLIHBR58KQ27:00000001, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /ws
Ocelot.Authentication.Middleware.AuthenticationMiddleware:Information: requestId: 0HLIHBR58KQ27:00000001, previousRequestId: no previous request id, message: No authentication needed for /videomanager/ws

[40m[32minfo[39m[22m[49m: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
requestId: 0HLIHBR58KQ27:00000001, previousRequestId: no previous request id, message: No authentication needed for /videomanager/ws

[40m[32minfo[39m[22m[49m: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0]
requestId: 0HLIHBR58KQ27:00000001, previousRequestId: no previous request id, message: /ws route does not require user to be authorised
Ocelot.Authorisation.Middleware.AuthorisationMiddleware:Information: requestId: 0HLIHBR58KQ27:00000001, previousRequestId: no previous request id, message: /ws route does not require user to be authorised
Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware:Debug: requestId: 0HLIHBR58KQ27:00000001, previousRequestId: no previous request id, message: Downstream url is ws://videomanager/ws
Ocelot.Requester.HttpClientHttpRequester:Debug: requestId: 0HLIHBR58KQ27:00000001, previousRequestId: no previous request id, message: Cache key for request is GET:http://localhost:4401/videomanager/ws

[40m[37mdbug[39m[22m[49m: Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware[0]
requestId: 0HLIHBR58KQ27:00000001, previousRequestId: no previous request id, message: Downstream url is ws://videomanager/ws

[40m[37mdbug[39m[22m[49m: Ocelot.Requester.HttpClientHttpRequester[0]
requestId: 0HLIHBR58KQ27:00000001, previousRequestId: no previous request id, message: Cache key for request is GET:http://localhost:4401/videomanager/ws
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://videomanager/ws  0

[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
Request starting HTTP/1.1 GET http://videomanager/ws  0


The thread 311 has exited with code 0 (0x0).
The thread 0x137 has exited with code 0 (0x0).
The thread 371 has exited with code 0 (0x0).
The thread 0x173 has exited with code 0 (0x0).
The thread 322 has exited with code 0 (0x0).
The thread 0x142 has exited with code 0 (0x0).


Exception thrown: 'System.IO.IOException' in System.Net.Sockets.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Net.WebSockets.WebSocketProtocol.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Net.Http.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Net.WebSockets.WebSocketProtocol.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Net.Http.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Net.Http.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll


Ocelot.Requester.Middleware.HttpRequesterMiddleware:Debug: requestId: 0HLIHBR58KQ26:00000001, previousRequestId: no previous request id, message: IHttpRequester returned an error, setting pipeline error


[40m[37mdbug[39m[22m[49m: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
requestId: 0HLIHBR58KQ26:00000001, previousRequestId: no previous request id, message: IHttpRequester returned an error, setting pipeline error
Ocelot.Requester.Middleware.HttpRequesterMiddleware:Warning: requestId: 0HLIHBR58KQ26:00000001, previousRequestId: no previous request id, message: Error making http request, exception: System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.IO.Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.RawConnectionStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.RawConnectionStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context)


[40m[1m[33mwarn[39m[22m[49m: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
requestId: 0HLIHBR58KQ26:00000001, previousRequestId: no previous request id, message: Error making http request, exception: System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
--- End of inner exception stack trace ---
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
at System.IO.Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
at System.Net.Http.HttpConnection.RawConnectionStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at System.Net.Http.HttpConnection.RawConnectionStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
at System.Net.Http.HttpConnection.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context)
Ocelot.Responder.Middleware.ResponderMiddleware:Warning: requestId: 0HLIHBR58KQ26:00000001, previousRequestId: no previous request id, message: Error Code: UnableToCompleteRequestError Message: Error making http request, exception: System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.IO.Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.RawConnectionStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.RawConnectionStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context) errors found in ResponderMiddleware. Setting error response for request path:/videomanager/ws, request method: GET


[40m[1m[33mwarn[39m[22m[49m: Ocelot.Responder.Middleware.ResponderMiddleware[0]
requestId: 0HLIHBR58KQ26:00000001, previousRequestId: no previous request id, message: Error Code: UnableToCompleteRequestError Message: Error making http request, exception: System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
--- End of inner exception stack trace ---
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
at System.IO.Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
at System.Net.Http.HttpConnection.RawConnectionStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at System.Net.Http.HttpConnection.RawConnectionStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
at System.Net.Http.HttpConnection.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context) errors found in ResponderMiddleware. Setting error response for request path:/videomanager/ws, request method: GET
Ocelot.Errors.Middleware.ExceptionHandlerMiddleware:Debug: requestId: 0HLIHBR58KQ26:00000001, previousRequestId: no previous request id, message: ocelot pipeline finished
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 96303.0762ms 500
```

**Comment by REPRESSION** [comment]
Solved my problem: I forgot to add    ``` app.UseWebSockets();``` to the gateway...
