### ISSUE TITLE
High availability?

### ISSUE THREAD

**Issue by rajput81** [ThreeMammals/Ocelot#782]
## Steps to Reproduce the Problem

  1.  Define multiple downstream hosts and ports under Reroute config as: 
"DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 3001
        },
        {
          "Host": "localhost",
          "Port": 2001
        },
        {
          "Host": "localhost",
          "Port": 5001
        }
      ],
  2. Define some load balancer options. None of the options works - LeastConnection/CookieStickySessions  etc

 "LoadBalancerOptions": {
        "Type": "RoundRobin" 
      },
  3. Stop the first host - "Host": "localhost", "Port": 3001, run the remaining. Request still goes to the first/dead host:3001 and below exception gets fired. 
The load balancer should detect this and only route requests to available/alive hosts.

[12:14:19 WRN] requestId:  0HLKCJ55GJUKP:00000003, previousRequestId: no previous request id, message: Error making http request, exception: System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at Ocelot.Tracing.Butterfly.ButterflyTracer.TracingSendAsync(ISpan span, HttpRequestMessage request, CancellationToken cancellationToken, Action`1 addTraceIdToRepo, Func`3 baseSendAsync)
   at Butterfly.Client.Tracing.ServiceTracerExtensions.TraceAsync[TResult](IServiceTracer tracer, ISpanBuilder spanBuilder, Func`2 operation)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context)

## Specifications

  - Version: Ocelot 13.0.0
  - Platform: Windows

**Comment by thiagoloureiro** [comment]
AFAIK there is no checks for this, what I do in my scenario I use Consul for service discovery and then when the service is unhealthy is automatically unregistered and Ocelot will not hit anymore :)
