### ISSUE TITLE
   at Ocelot.Errors.Middleware.ExceptionHandlerMiddleware.Invoke(DownstreamContext context), inner exception message The format of value 'MicroMessenger/7.0.3(0x17000321) NetType/WIFI Language/zh_CN' is invalid., inner exception

### ISSUE THREAD

**Issue by eit520** [ThreeMammals/Ocelot#800]
## Expected Behavior / New Feature
Ocelot.Errors.Middleware.ExceptionHandlerMiddleware:Error: requestId: 80004aa4-0000-9b00-b63f-84710c7967bb, previousRequestId: no previous request id, message:
 Exception caught in global error handler, exception message: Unable to connect to the remote server, exception stack:    
 at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Ocelot.WebSockets.Middleware.WebSocketsProxyMiddleware.Proxy(HttpContext context, String serverEndpoint)
   at Ocelot.WebSockets.Middleware.WebSocketsProxyMiddleware.Invoke(DownstreamContext context)
   at Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware.Invoke(DownstreamContext context)
   at Ocelot.LoadBalancer.Middleware.LoadBalancingMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Request.Middleware.DownstreamRequestInitialiserMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Middleware.Multiplexer.Multiplexer.Fire(DownstreamContext context, OcelotRequestDelegate next)
   at Ocelot.Middleware.Multiplexer.Multiplexer.Multiplex(DownstreamContext context, ReRoute reRoute, OcelotRequestDelegate next)
   at Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Middleware.Pipeline.MapWhenMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Errors.Middleware.ExceptionHandlerMiddleware.Invoke(DownstreamContext context), inner exception message The format of value 'MicroMessenger/7.0.3(0x17000321) NetType/WIFI Language/zh_CN' is invalid., inner exception stack    

   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(String name, String value)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options) RequestId: 80004aa4-0000-9b00-b63f-84710c7967bb, exception: System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server ---> 

   System.FormatException: The format of value 'MicroMessenger/7.0.3(0x17000321) NetType/WIFI Language/zh_CN' is invalid.
   
   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(String name, String value)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Ocelot.WebSockets.Middleware.WebSocketsProxyMiddleware.Proxy(HttpContext context, String serverEndpoint)
   at Ocelot.WebSockets.Middleware.WebSocketsProxyMiddleware.Invoke(DownstreamContext context)
   at Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware.Invoke(DownstreamContext context)
   at Ocelot.LoadBalancer.Middleware.LoadBalancingMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Request.Middleware.DownstreamRequestInitialiserMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Middleware.Multiplexer.Multiplexer.Fire(DownstreamContext context, OcelotRequestDelegate next)
   at Ocelot.Middleware.Multiplexer.Multiplexer.Multiplex(DownstreamContext context, ReRoute reRoute, OcelotRequestDelegate next)
   at Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Middleware.Pipeline.MapWhenMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Errors.Middleware.ExceptionHandlerMiddleware.Invoke(DownstreamContext context)

## Steps to Reproduce the Problem

  1.WeChat applet  Send WebSocket请求
  1.
  1.

## Specifications

  - Version:13
  - Platform:  Windows 2016
  - Subsystem:

**Comment by thiagoloureiro** [comment]
please, need more details, just the error message didn't help.

**Comment by eit520** [comment]
WeChat small program when establishing a WebSocket request. The request that is made will fail when the connection is established. The exception information is as I sent it above.

**Comment by eit520** [comment]
> please, need more details, just the error message didn't help.

WeChat small program when establishing a WebSocket request. The request that is made will fail when the connection is established. The exception information is as I sent it above.

**Comment by eit520** [comment]
> please, need more details, just the error message didn't help.
When using Ocelot Api Gateway, User-agent is "MicroMessenger/7.0.3(0x17000321) NetType/WIFI Language/zh_CN" throw an exception
It's OK to connect directly to ASP.net core WebAPI

**Comment by raman-m** [comment]
@eit520
Please, reproduce and confirm this bug in latest [v22](https://github.com/ThreeMammals/Ocelot/releases) please with possible reopening.
