### ISSUE TITLE
Unexplained Http 50x Errors Under Load

### ISSUE THREAD

**Issue by sunburntstrat** [ThreeMammals/Ocelot#817]
Hi we are currently performing some basic load tests using Ocelot as a Gateway to backend APIs. For the most part it's working well however we have found that once we cross a certain threshold of requests per second (around 40 rps), we start seeing unexplained 500 responses with the following error message raised in Ocelot (in HttpClientHttpRequester).

## Exception Stack Trace
Error Code: UnableToCompleteRequestError Message: Error making http request, exception: System.Net.Http.HttpRequestException: The server returned an invalid or unrecognized response.
   at System.Net.Http.HttpConnection.ThrowInvalidHttpResponse()
   at System.Net.Http.HttpConnection.ParseStatusLine(Span`1 line, HttpResponseMessage response)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context) errors found in ResponderMiddleware.

## Environment Setup

- Ocelot 13.0 running as .net core web app.
- 2 App Servers each hosting Ocelot and fronted by ILB.
- DownstreamHost pointing to ILB fronting 2 App Servers

No QoS, RateLimiting etc enabled
Polly Package not installed
## -------------------------------------------

Is this behaviour something you have come across before? 

Thanks.

**Comment by sunburntstrat** [comment]
So it turns out this was an issue with the configuration of the test runner rather than the Gateway. 
Oddly the problem did not manifest when going direct to the APIs.
