### ISSUE TITLE
Upgrade to FluentValidation 8.x

### ISSUE THREAD

**Issue by emiliovmq** [ThreeMammals/Ocelot#832]
## Expected Behavior / New Feature
Upgrade to FluentValidation 8.1.3

## Actual Behavior / Motivation for New Feature
Ocelot is currently using FluentValidation 7.6.104
<PackageReference Include="FluentValidation" Version="7.6.104" />
If I use a package or reference a project using FluentValidation with a version greater than 7.6.104, like 8.1.3, the Ocelot starts throwing the exception:

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Method not found: 'Void FluentValidation.AbstractValidator`1.When(System.Func`2<!0,Boolean>, System.Action)'.)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at OneSpaWorld.Olympus.WebPreBooking.ApiGateway.Startup.Configure(IApplicationBuilder app, CorsSettings corsSettings) in C:\Work\Src\dotnet\workspace\repos\Olympus\OneSpaWorld.Olympus.WebPreBooking.ApiGateway\OneSpaWorld.Olympus.WebPreBooking.ApiGateway\Startup.cs:line 117

Inner Exception 1:
MissingMethodException: Method not found: 'Void FluentValidation.AbstractValidator`1.When(System.Func`2<!0,Boolean>, System.Action)'.

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version: 13.0.0
  - Platform: .Net Core 2.2 (2.2.3 / .NET Standard 2.0) - SDK 2.2.105
  - Subsystem:

**Comment by thiagoloureiro** [comment]
I will update the package and release soon.

**Comment by emiliovmq** [comment]
Thank you, sir.
