### ISSUE TITLE
Device not configured

### ISSUE THREAD

**Issue by arquehi** [ThreeMammals/Ocelot#848]
## Expected Behavior / New Feature
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:7000/api/values  
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:7000/api/values  
[40m[37mdbug[39m[22m[49m: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      requestId: 0HLLLQM38D5VR:00000002, previousRequestId: no previous request id, message: ocelot pipeline started
Ocelot.Errors.Middleware.ExceptionHandlerMiddleware:Debug: requestId: 0HLLLQM38D5VR:00000002, previousRequestId: no previous request id, message: ocelot pipeline started
[40m[37mdbug[39m[22m[49m: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      requestId: 0HLLLQM38D5VR:00000002, previousRequestId: no previous request id, message: Upstream url path is /api/values
Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware:Debug: requestId: 0HLLLQM38D5VR:00000002, previousRequestId: no previous request id, message: Upstream url path is /api/values
[40m[37mdbug[39m[22m[49m: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      requestId: 0HLLLQM38D5VR:00000002, previousRequestId: no previous request id, message: downstream templates are /api/{everything}
Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware:Debug: requestId: 0HLLLQM38D5VR:00000002, previousRequestId: no previous request id, message: downstream templates are /api/{everything}
[40m[32minfo[39m[22m[49m: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
      requestId: 0HLLLQM38D5VR:00000002, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /api/{everything}
Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware:Information: requestId: 0HLLLQM38D5VR:00000002, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /api/{everything}
[40m[32minfo[39m[22m[49m: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 0HLLLQM38D5VR:00000002, previousRequestId: no previous request id, message: No authentication needed for /api/values
Ocelot.Authentication.Middleware.AuthenticationMiddleware:Information: requestId: 0HLLLQM38D5VR:00000002, previousRequestId: no previous request id, message: No authentication needed for /api/values
[40m[32minfo[39m[22m[49m: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0]
      requestId: 0HLLLQM38D5VR:00000002, previousRequestId: no previous request id, message: /api/{everything} route does not require user to be authorised
Ocelot.Authorisation.Middleware.AuthorisationMiddleware:Information: requestId: 0HLLLQM38D5VR:00000002, previousRequestId: no previous request id, message: /api/{everything} route does not require user to be authorised
[40m[37mdbug[39m[22m[49m: Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware[0]
      requestId: 0HLLLQM38D5VR:00000002, previousRequestId: no previous request id, message: Downstream url is http://localhost:7002/api/values
Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware:Debug: requestId: 0HLLLQM38D5VR:00000002, previousRequestId: no previous request id, message: Downstream url is http://localhost:7002/api/values
Ocelot.Requester.Middleware.HttpRequesterMiddleware:Debug: requestId: 0HLLLQM38D5VR:00000002, previousRequestId: no previous request id, message: IHttpRequester returned an error, setting pipeline error
[40m[37mdbug[39m[22m[49m: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HLLLQM38D5VR:00000002, previousRequestId: no previous request id, message: IHttpRequester returned an error, setting pipeline error
[40m[1m[33mwarn[39m[22m[49m: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HLLLQM38D5VR:00000002, previousRequestId: no previous request id, message: Error making http request, exception: System.Net.Http.HttpRequestException: Device not configured ---> System.Net.Sockets.SocketException: Device not configured
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         at System.Threading.Tasks.ValueTask`1.get_Result()
         at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Threading.Tasks.ValueTask`1.get_Result()
         at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
         at System.Threading.Tasks.ValueTask`1.get_Result()
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
         at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context)
Ocelot.Requester.Middleware.HttpRequesterMiddleware:Warning: requestId: 0HLLLQM38D5VR:00000002, previousRequestId: no previous request id, message: Error making http request, exception: System.Net.Http.HttpRequestException: Device not configured ---> System.Net.Sockets.SocketException: Device not configured
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context)
[40m[1m[33mwarn[39m[22m[49m: Ocelot.Responder.Middleware.ResponderMiddleware[0]
      requestId: 0HLLLQM38D5VR:00000002, previousRequestId: no previous request id, message: Error Code: UnableToCompleteRequestError Message: Error making http request, exception: System.Net.Http.HttpRequestException: Device not configured ---> System.Net.Sockets.SocketException: Device not configured
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         at System.Threading.Tasks.ValueTask`1.get_Result()
         at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Threading.Tasks.ValueTask`1.get_Result()
         at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
         at System.Threading.Tasks.ValueTask`1.get_Result()
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
         at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context) errors found in ResponderMiddleware. Setting error response for request path:/api/values, request method: GET
Ocelot.Responder.Middleware.ResponderMiddleware:Warning: requestId: 0HLLLQM38D5VR:00000002, previousRequestId: no previous request id, message: Error Code: UnableToCompleteRequestError Message: Error making http request, exception: System.Net.Http.HttpRequestException: Device not configured ---> System.Net.Sockets.SocketException: Device not configured
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context) errors found in ResponderMiddleware. Setting error response for request path:/api/values, request method: GET
[40m[37mdbug[39m[22m[49m: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      requestId: 0HLLLQM38D5VR:00000002, previousRequestId: no previous request id, message: ocelot pipeline finished
Ocelot.Errors.Middleware.ExceptionHandlerMiddleware:Debug: requestId: 0HLLLQM38D5VR:00000002, previousRequestId: no previous request id, message: ocelot pipeline finished
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 183.9407ms 500 
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 183.9407ms 500 

## Specifications

  - Version: all version
  - Platform: visual studio for mac  asp.net core 2.2
  - Subsystem: macOS 10.14.4

**Comment by arquehi** [comment]
I`m learning ocelot in the past two days within visual studio for mac. dev for the demo with API and get some problem. finally, I find the DNS was set to 8.8.8.8. so I del it and the application running well.
