### ISSUE TITLE
app exit after consul down

### ISSUE THREAD

**Issue by rider11-dev** [ThreeMammals/Ocelot#866]
Hello,I'm using configuration in consul.
And I see the FileConfigurationPoller  fetch data from consul as IHostedService.
My problom is ,after my app start normally for a while,I close the consul server,and got the error blow:
 at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Consul.GetRequest`1.Execute(CancellationToken ct)
   at Consul.KV.Get(String key, QueryOptions q, CancellationToken ct)
   at Ocelot.Configuration.Repository.ConsulFileConfigurationRepository.Get()
   at Ocelot.Configuration.Repository.FileConfigurationPoller.Poll()
   at Ocelot.Configuration.Repository.FileConfigurationPoller.<StartAsync>b__9_0(Object x)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
**Thats right ,but my app exited after the error.**
Why is this ?

**Comment by raman-m** [comment]
> at System.Net.Http.ConnectHelper.**ConnectAsync**(String host, Int32 port, CancellationToken cancellationToken)
Why is this?

Because you have network connection problem! :rofl:
