### ISSUE TITLE
Only 'http' and 'https' schemes are allowed

### ISSUE THREAD

**Issue by juli516b** [ThreeMammals/Ocelot#878]
## Expected Behavior / New Feature
Returning a list of JSON objects

## Actual Behavior / Motivation for New Feature
Returning 500

## Following LOG
`Request starting HTTP/1.1 GET http://localhost:7000/requests
dbug: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      requestId: 0HLMI34GM19DC:00000002, previousRequestId: no previous request id, message: ocelot pipeline started
dbug: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      requestId: 0HLMI34GM19DC:00000002, previousRequestId: no previous request id, message: Upstream url path is /requests
dbug: Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware[0]
      requestId: 0HLMI34GM19DC:00000002, previousRequestId: no previous request id, message: downstream templates are /api/requests
info: Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware[0]
      requestId: 0HLMI34GM19DC:00000002, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /api/requests
info: Ocelot.Authentication.Middleware.AuthenticationMiddleware[0]
      requestId: 0HLMI34GM19DC:00000002, previousRequestId: no previous request id, message: No authentication needed for /requests
info: Ocelot.Authorisation.Middleware.AuthorisationMiddleware[0]
      requestId: 0HLMI34GM19DC:00000002, previousRequestId: no previous request id, message: /api/requests route does not require user to be authorised
dbug: Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware[0]
      requestId: 0HLMI34GM19DC:00000002, previousRequestId: no previous request id, message: Downstream url is localhost:7001/api/requests
dbug: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HLMI34GM19DC:00000002, previousRequestId: no previous request id, message: IHttpRequester returned an error, setting pipeline error
warn: Ocelot.Requester.Middleware.HttpRequesterMiddleware[0]
      requestId: 0HLMI34GM19DC:00000002, previousRequestId: no previous request id, message: Error making http request, exception: System.ArgumentException: Only 'http' and 'https' schemes are allowed.
      Parameter name: value
         at System.Net.Http.HttpRequestMessage.set_RequestUri(Uri value)
         at Ocelot.Request.Middleware.DownstreamRequest.ToHttpRequestMessage()
         at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context)
warn: Ocelot.Responder.Middleware.ResponderMiddleware[0]
      requestId: 0HLMI34GM19DC:00000002, previousRequestId: no previous request id, message: Error Code: UnableToCompleteRequestError Message: Error making http request, exception: System.ArgumentException: Only 'http' and 'https' schemes are allowed.
      Parameter name: value
         at System.Net.Http.HttpRequestMessage.set_RequestUri(Uri value)
         at Ocelot.Request.Middleware.DownstreamRequest.ToHttpRequestMessage()
         at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context) errors found in ResponderMiddleware. Setting error response for request path:/requests, request method: GET
dbug: Ocelot.Errors.Middleware.ExceptionHandlerMiddleware[0]
      requestId: 0HLMI34GM19DC:00000002, previousRequestId: no previous request id, message: ocelot pipeline finished
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 177.1291ms 500`

## Specifications

  - Version: 13.5.0
  - Platform: Windows

**Comment by juli516b** [comment]
Fixed after type
