### ISSUE TITLE
Problem with POSTing big files

### ISSUE THREAD

**Issue by dmitriifilonenko** [ThreeMammals/Ocelot#884]
Currently Ocelot doesn't allow POST requests with big bodies. Effectively it forbids uploading relatively big files.

> "Error Code: UnmappableRequestError Message: Error when parsing incoming request, exception: Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Request body too large.
>    at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.ForContentLength.OnReadStarting()
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.TryInit()
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.CopyToAsync(Stream destination, CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.CopyToAsyncInternal(Stream destination, CancellationToken cancellationToken)
>    at Ocelot.Request.Mapper.RequestMapper.ToByteArray(Stream stream)
>    at Ocelot.Request.Mapper.RequestMapper.MapContent(HttpRequest request)
>    at Ocelot.Request.Mapper.RequestMapper.Map(HttpRequest request) errors found in ResponderMiddleware. Setting error response for request path:/<some path>, request method: POST"

This can be worked around on the application level:
```
WebHost.CreateDefaultBuilder(args)
                .UseKestrel(options =>
                {
                    options.Limits.MaxRequestBodySize = null;
                })
```
But it would be much better if it was possible on request level, preferebely as a part of ReRoute configuration.

Also it's not completely clear if Ocelot manages to resend request with big content. I face another issue:

> "Error making http request, exception: System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: Unable to read data from the transport connection: Broken pipe. ---> System.Net.Sockets.SocketException: Broken pipe
>    --- End of inner exception stack trace ---
>    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
>    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
>    at System.Net.Http.HttpConnection.WriteAsync(ReadOnlyMemory`1 source)
>    at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask)
>    --- End of inner exception stack trace ---
>    at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask)
>    at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)

Though it's not yet clear is the problem is in Ocelot.

**Comment by daoye** [comment]
I have the same problem.

But, when I set the Ocelot and  Upstream's  "options.Limits.MaxRequestBodySize = null;" 

It's fixed.

**Comment by Keerthikan** [comment]
Reroute configuration would be a better option, than enabling this application wide.

**Comment by maulik-modi** [comment]
#928 Chunked Encoding

**Comment by raman-m** [comment]
Fixed by #1724 #1824
