### ISSUE TITLE
Ocelot Authorization using custom auth

### ISSUE THREAD

**Issue by yrox** [ThreeMammals/Ocelot#886]
Hi,

**[Setup]**
i'm trying to run this sample https://github.com/kasitimo/MyGatewayAPI 

with next Program.cs:
```
public static void Main(string[] args)
        {
            new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    config
                        .SetBasePath(hostingContext.HostingEnvironment.ContentRootPath)
                        .AddJsonFile("appsettings.json", true, true)
                        .AddJsonFile($"appsettings.{hostingContext.HostingEnvironment.EnvironmentName}.json", true, true)
                        .AddJsonFile("ocelot.json")
                        .AddEnvironmentVariables();
                })
                .ConfigureServices(s =>
                {
                    s.AddAuthentication(options =>
                        {
                            options.DefaultScheme = "CustomAuth";
                            //options.DefaultAuthenticateScheme = "CustomScheme";
                            //options.DefaultChallengeScheme = "CustomScheme";
                        })
                        .AddCustomAuth("CustomAuth", o => { });
                    s.AddOcelot();
                })
                .ConfigureLogging((hostingContext, logging) =>
                {
                    //add your logging
                })
                .UseIISIntegration()
                .Configure(app =>
                {
                    app.UseAuthentication();
                    app.UseOcelot().Wait();
                })
                .UseUrls("http://localhost:9000")
                .Build()
                .Run();
        }
```
**[Problem]**
but i'm getting next error: 

> exception message: Object reference not set to an instance of an object., exception stack:    at Ocelot.Authentication.Middleware.AuthenticationMiddleware.Invoke(DownstreamContext context)

here is the whole output:

```
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:9000/api/Test
SSOGateway.auth.CustomAuthHandler:Debug: AuthenticationScheme: ApiSecurity was successfully authenticated.
Ocelot.Errors.Middleware.ExceptionHandlerMiddleware:Debug: requestId: 0HLMNIT9I6REN:00000004, previousRequestId: no previous request id, message: ocelot pipeline started
Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware:Debug: requestId: 0HLMNIT9I6REN:00000004, previousRequestId: no previous request id, message: Upstream url path is /redirection
Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware:Debug: requestId: 0HLMNIT9I6REN:00000004, previousRequestId: no previous request id, message: downstream templates are /
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\2.2.3\Microsoft.AspNetCore.Http.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware:Information: requestId: 0HLMNIT9I6REN:00000004, previousRequestId: no previous request id, message: EndpointRateLimiting is not enabled for /
Ocelot.Authentication.Middleware.AuthenticationMiddleware:Information: requestId: 0HLMNIT9I6REN:00000004, previousRequestId: no previous request id, message: /redirection is an authenticated route. AuthenticationMiddleware checking if client is authenticated
SSOGateway.auth.CustomAuthHandler:Debug: AuthenticationScheme: ApiSecurity was successfully authenticated.
Ocelot.Errors.Middleware.ExceptionHandlerMiddleware:Debug: requestId: 0HLMNIT9I6REN:00000004, previousRequestId: no previous request id, message: error calling middleware
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.3\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.3\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Ocelot.Errors.Middleware.ExceptionHandlerMiddleware:Error: requestId: 0HLMNIT9I6REN:00000004, previousRequestId: no previous request id, message: Exception caught in global error handler, exception message: Object reference not set to an instance of an object., exception stack:    at Ocelot.Authentication.Middleware.AuthenticationMiddleware.Invoke(DownstreamContext context)
   at Ocelot.RequestId.Middleware.ReRouteRequestIdMiddleware.Invoke(DownstreamContext context)
   at Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Request.Middleware.DownstreamRequestInitialiserMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Headers.Middleware.HttpHeadersTransformationMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Security.Middleware.SecurityMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Middleware.Multiplexer.Multiplexer.Fire(DownstreamContext context, OcelotRequestDelegate next)
   at Ocelot.Middleware.Multiplexer.Multiplexer.Multiplex(DownstreamContext context, ReRoute reRoute, OcelotRequestDelegate next)
   at Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Responder.Middleware.ResponderMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Middleware.Pipeline.MapWhenMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Errors.Middleware.ExceptionHandlerMiddleware.Invoke(DownstreamContext context) RequestId: 0HLMNIT9I6REN:00000004, exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ocelot.Authentication.Middleware.AuthenticationMiddleware.Invoke(DownstreamContext context)
   at Ocelot.RequestId.Middleware.ReRouteRequestIdMiddleware.Invoke(DownstreamContext context)
   at Ocelot.RateLimit.Middleware.ClientRateLimitMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Request.Middleware.DownstreamRequestInitialiserMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Headers.Middleware.HttpHeadersTransformationMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Security.Middleware.SecurityMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Middleware.Multiplexer.Multiplexer.Fire(DownstreamContext context, OcelotRequestDelegate next)
   at Ocelot.Middleware.Multiplexer.Multiplexer.Multiplex(DownstreamContext context, ReRoute reRoute, OcelotRequestDelegate next)
   at Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Responder.Middleware.ResponderMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Middleware.Pipeline.MapWhenMiddleware.Invoke(DownstreamContext context)
   at Ocelot.Errors.Middleware.ExceptionHandlerMiddleware.Invoke(DownstreamContext context)
```
**[Question]**
Is it something wrong with the setup or this is about ocelot issue itself?

Thanks for any help!

**Comment by yrox** [comment]
The problem was with the interior setup :)
