### ISSUE TITLE
Quality of Service - Configuration

### ISSUE THREAD

**Issue by ankitvijay** [ThreeMammals/Ocelot#908]
## Background
- As per the [Quality of Service](https://ocelot.readthedocs.io/en/latest/features/qualityofservice.html), documentation we can set up `TimeoutValue` in isolation of the `ExceptionsAllowedBeforeBreaking` and `DurationOfBreak` options. I'm trying to only use `TimeoutValue` property without the other two.
 
## Expected Behavior
- Expected Behavior is that if I have just configure `TimeoutValue` then I should be able to call the API Gateway without any issue.

## Actual Behavior
- Configuring just the `TimeoutValue` returns `500 Internal Server Error`. Here are logs:
`````````````````````````
[WRN] requestId: 80000010-0007-ff00-b63f-84710c7967bb, previousRequestId: no previous request id, message: Error making http request, exception: System.ArgumentException: The enumerable of policies to form the wrap must contain at least two policies.
Parameter name: policies
   at Polly.Policy.WrapAsync(IAsyncPolicy[] policies) in C:\projects\polly\src\Polly.Shared\Wrap\PolicyWrapSyntaxAsync.cs:line 93
   at Ocelot.Provider.Polly.PollyCircuitBreakingDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context)

[WRN] requestId: 80000010-0007-ff00-b63f-84710c7967bb, previousRequestId: no previous request id, message: Error Code: UnableToCompleteRequestError Message: Error making http request, exception: System.ArgumentException: The enumerable of policies to form the wrap must contain at least two policies.
Parameter name: policies
   at Polly.Policy.WrapAsync(IAsyncPolicy[] policies) in C:\projects\polly\src\Polly.Shared\Wrap\PolicyWrapSyntaxAsync.cs:line 93
   at Ocelot.Provider.Polly.PollyCircuitBreakingDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context) errors found in ResponderMiddleware. Setting error response for request path:/api/HomeAssessment/Codification/slowService/20, request method: GET
2019-05-31 11:54:27.395 +10:00 [ERR] <End Request> GET /api/HomeAssessment/Codification/slowService/20 500 8ms
`````````````````````````

## Additional Information
This issue can be also be reproduced with `Ocelot.AcceptanceTests` -> `PollyQoSTests`. If we remove property  `ExceptionsAllowedBeforeBreaking` from `should_timeout` and `should_not_timeout` methods, we get `InternalServerError`. As per documentation, this should not be case.

**Comment by kvskranthikumar** [comment]
Any solution?
I am also facing the same issue.

**Comment by midco-tylerjo** [comment]
Same issue for me.  Appear to be getting the same error even with all 3 options provided.  Would like to be able to only set TimeoutValue.

"QoSOptions": {
    "ExceptionsAllowedBeforeBreaking":3,
    "DurationOfBreak":1000,
    "TimeoutValue":5000
}

**Comment by suadev** [comment]
@TomPallister Did you archived this project or not?

**Comment by jfbueno** [comment]
I'm using Ocelot version 17.0 (the latest on nuget) and still having this issue. Is there any workaround for this?
