### ISSUE TITLE
Error making http request

### ISSUE THREAD

**Issue by jonny-xhl** [ThreeMammals/Ocelot#925]
## logs
```
warn: Ocelot.Responder.Middleware.ResponderMiddleware[0]
      requestId: 0HLNFQME9O0DV:00000001, previousRequestId: no previous request id, message: Error Code: UnableToCompleteRequestError Message: Error making http request, 
	exception: System.Net.Http.HttpRequestException: 请求的名称有效，但是找不到请求的类型的数据。 
	---> System.Net.Sockets.SocketException: 请求的名称有效，但是找不到请求的类型的数据。
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         at System.Threading.Tasks.ValueTask`1.get_Result()
         at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Threading.Tasks.ValueTask`1.get_Result()
         at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
         at System.Threading.Tasks.ValueTask`1.get_Result()
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
         at Ocelot.Requester.HttpClientHttpRequester.GetResponse(DownstreamContext context) errors found in ResponderMiddleware. Setting error response for request path:/auth/token, 
	 request method: POST
```
## consul server config
```
{
  "encrypt": "7TnJPB4lKtjEcCWWjN6jSA==",
  "services": [
    {
      "id": "Service1",
      "name": "Service1",
      "tags": [ "Service1" ],
      "address": "192.168.1.139",
      "port": 5011,
      "checks": [
        {
          "id": "Service1_Check",
          "name": "Service1_Check",
          "http": "http://192.168.1.139:5011/api/health",
          "interval": "10s",
          "tls_skip_verify": false,
          "method": "GET",
          "timeout": "1s"
        }
      ]
    },
    {
      "id": "Service2",
      "name": "Service2",
      "tags": [ "Service2" ],
      "address": "192.168.1.139",
      "port": 5021,
      "checks": [
        {
          "id": "Service2_Check",
          "name": "Service2_Check",
          "http": "http://192.168.1.139:5021/api/health",
          "interval": "10s",
          "tls_skip_verify": false,
          "method": "GET",
          "timeout": "1s"
        }
      ]
    },
    {
      "id": "IdentityServer",
      "name": "IdentityServer",
      "tags": [ "IdentityServer-tag" ],
      "address": "192.168.1.139",
      "port": 5001,
      "checks": [
        {
          "id": "IdentityServer_Check",
          "name": "IdentityServer_Check",
          "http": "http://192.168.1.139:5001/api/values",
          "interval": "10s",
          "tls_skip_verify": false,
          "method": "GET",
          "timeout": "1s"
        }
      ]
    },
    {
      "id": "APIGateway",
      "name": "APIGateway",
      "tags": [ "APIGateway" ],
      "address": "192.168.1.139",
      "port": 1001
    }
  ]
}
```
## ocelot application server config
```
{
  "ReRoutes": [
    //identityserver4  token
    {

      "DownstreamPathTemplate": "/connect/token",
      "DownstreamScheme": "http",
      /*"DownstreamHostAndPorts": [
        {
          "Host": "192.168.1.139",
          "Port": "5001"
        }
      ],*/
      "ServiceName":"IdentityServer",
      "UpstreamPathTemplate": "/auth/token",
      "UpstreamHttpMethod": ["Post"],
      "UseServiceDiscovery": false,
      "DangerousAcceptAnyServerCertificateValidator": false
    },
    // API:Service1
    {
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "service1Identity",
        "AllowedScopes": []
      },
      "DownstreamPathTemplate": "/api/{url}",
      "DownstreamScheme": "http",
      /*"DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": "5011"
        }
      ],*/
      "ServiceName":"Service1",
      "UpstreamPathTemplate": "/Service1/{url}",
      "UpstreamHttpMethod": [ "Get", "Post" ],
      "UseServiceDiscovery": false,
      "DangerousAcceptAnyServerCertificateValidator": false
    },
    // API:Service2
    {
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "service2Idnetity",
        "AllowedScopes": []
      },
      "DownstreamPathTemplate": "/api/{url}",
      "DownstreamScheme": "http",
      /*"DownstreamHostAndPorts": [
        {
          "Host": "192.168.1.139",
          "Port": "5021"
        }
      ],*/
      "ServiceName":"Service2",
      "UpstreamPathTemplate": "/Service2/{url}",
      "UpstreamHttpMethod": [ "Get", "Post" ],
      "UseServiceDiscovery": false,
      "DangerousAcceptAnyServerCertificateValidator": false
    }
  ],
  "GlobalConfiguration": {
    "ServiceDiscoveryProvider": {
      "Host": "192.168.1.181",
      "Port": 8500,
      "Type": "Consul"
    },
    "RateLimitOptions": {

      "ClientIdHeader": "client_id",

      "QuotaExceededMessage": "Too Many Requests!!!",

      "DisableRateLimitHeaders": false

    }
  }
}
```
1、when I request http://192.168.1.139:1001/auth/token and then response 500 httpstatuscode.

**Comment by CQJonnyLin** [comment]
Config ReRoutes use DownstreamHostAndPorts can success,but use ServiceName throw exception.

**Comment by yuft** [comment]
I guess this is more of a Consul health check definition problem, not Ocelot related.

>  HTTP checks also support TLS. By default, a valid TLS certificate is expected. Certificate verification can be turned off by setting the tls_skip_verify field to true in the check definition.

https://www.consul.io/docs/agent/checks.html

**Comment by CQJonnyLin** [comment]
I try setting tls_skip_verify field to true,but also throw the exception

**Comment by CQJonnyLin** [comment]
@yuft ,Can you tell me Consul health check definetion where is problem.
The  ![consul web ui](https://user-images.githubusercontent.com/29520329/59476942-9a2dd400-8e85-11e9-8990-8a92198f246f.png) show check success.

**Comment by yuft** [comment]
Just saw you had  "UseServiceDiscovery": false, maybe you can remove it and see if it makes any difference.

**Comment by CQJonnyLin** [comment]
> Just saw you had "UseServiceDiscovery": false, maybe you can remove it and see if it makes any difference.
Now,I setting sigle Consul server can success.
Don't change Ocelot config. 
![consul web ui](https://user-images.githubusercontent.com/29520329/59477786-59d05500-8e89-11e9-8c23-c39b953bbc46.png)

![Post](https://user-images.githubusercontent.com/29520329/59477887-cc413500-8e89-11e9-81f9-688ba4fbb782.png)

**Comment by raman-m** [comment]
@jonny-xhl 
I believe PRs #1670, #1377 should resolve your problem. If Not then it seems it's Consul configuration issue.
Let me know testing results please!
